### ISSUE TITLE
reference git submodules

### ISSUE THREAD

**Issue by heissenschorse** [babelouest/ulfius#1]
Hey,
i tried to use your project ulfius at commit 62f71b9e6e5e6a6b4a24e80208da6332fbfb56bd
this project looks very nice !
but i get a error while init the submodules.

could it be that the url in the .gitmodules file
git@github.com:babelouest/orcania.git
should look like:
https://github.com/babelouest/orcania.git ?
so the whole  .gitmodules file: 
[submodule "lib/orcania"]
	path = lib/orcania
	url = https://github.com/babelouest/orcania.git
[submodule "lib/yder"]
	path = lib/yder
	url = https://github.com/babelouest/yder.git
 
Could you might double check this ? 

Also i use usually to checkout the submodules the follwoing commands:
git submodule init
git submodule update

afterwards everything compiles fantastic 

thanks
heissenschorse

**Comment by babelouest** [comment]
You're right, thanks for pointing out, I've used the ssh access because of my default github configuration, but an https access is way better for everyone.

I've fixed it in the https://github.com/babelouest/ulfius/commit/c8e9cc52878eaa326b0a30b7a7a3371ef1553994 release.
