### ISSUE TITLE
won't build as per instructions

### ISSUE THREAD

**Issue by BryanDollery** [babelouest/ulfius#10]
I've followed the instructions to build from source, but the code fails in orcania.c:

make[1]: Entering directory `/work/ulfius/lib/orcania'
gcc -c -fPIC -Wall -D_REENTRANT -O3 orcania.c
orcania.c: In function 'trimwhitespace':
orcania.c:382:3: warning: implicit declaration of function 'isspace' [-Wimplicit-function-declaration]
   while(isspace((unsigned char)*str)) str++;
   ^

**Comment by babelouest** [comment]
Hi @BryanDollery 

My bad, this should be fixed now, thanks

Let me know if you still have issues

**Comment by babelouest** [comment]
Hello,

any update on your issue? Were you able to build the library?

**Comment by BryanDollery** [comment]
Sorry, was off work. I now get a 'protocol' error:

root@7557ca4322c3:/work/ulfius# make                                              
cd lib/orcania && make                                                            
make[1]: Entering directory `/work/ulfius/lib/orcania'                            
gcc -c -fPIC -Wall -D_REENTRANT -O3 orcania.c                                     
gcc -shared -Wl,-soname,liborcania.so -o liborcania.so.0.9 orcania.o -lc -ljansson
ln -sf liborcania.so.0.9 liborcania.so                                            
ln: failed to create symbolic link 'liborcania.so': Protocol error                
make[1]: *** [liborcania.so] Error 1                                              
make[1]: Leaving directory `/work/ulfius/lib/orcania'                             
make: *** [libulfius.so] Error 2

**Comment by babelouest** [comment]
`failed to create symbolic link` doesn't say much to me.
What OS/version are you using ? Do you have the proper credentials in the folder?

I tried with a fresh clone/build and it worked fine on my machine.
You could try again with a new clone and restart the procedure as explained in the `INSTALL.md` file.
