### ISSUE TITLE
IPV6 Support

### ISSUE THREAD

**Issue by saohimank** [babelouest/ulfius#104]
From my understanding, the ulfius library does not support IPV6, as the bind_address is of type struct sockaddr_in, wherein for IPV6 the MHD requires sockaddr_in6 for IPV6. If my understanding is wrong, please suggest on how to use IPV6. 

From MHD documentation,

MHD_OPTION_SOCK_ADDR

Bind daemon to the supplied socket address. This option should be followed by a struct sockaddr *. **If MHD_USE_IPv6 is specified, the struct sockaddr* should point to a struct sockaddr_in6**, otherwise to a struct sockaddr_in. If this option is not specified, the daemon will listen to incoming connections from anywhere. If you use this option, the ’port’ argument from MHD_start_daemon is ignored and the port from the given struct sockaddr * will be used instead.

**Comment by babelouest** [comment]
Hello,

I haven't made any specific change for IPV6, so the default libmicrohttpd option is used. In this case, it only binds to IPV4 addresses, see [MHD_USE_IPv6 flag](https://www.gnu.org/software/libmicrohttpd/manual/libmicrohttpd.html#microhttpd_002dconst).

I will make the change in the next release to support IPV4 only, IPV6 only or both.
Meanwhile, if you want to listen to any IPV4 or IPV6 address, you can apply the following patch:

```patch
diff --git a/src/ulfius.c b/src/ulfius.c
index 3bf04e4..5a7f3c6 100644
--- a/src/ulfius.c
+++ b/src/ulfius.c
@@ -774,7 +774,7 @@ static int ulfius_webservice_dispatcher (void * cls, struct MHD_Connection * con
  *
  */
 static struct MHD_Daemon * ulfius_run_mhd_daemon(struct _u_instance * u_instance, const char * key_pem, const char * cert_pem, const char * root_ca_perm) {
-  unsigned int mhd_flags = MHD_USE_AUTO;
+  unsigned int mhd_flags = MHD_USE_AUTO | MHD_USE_DUAL_STACK;
   int index;


 #ifdef DEBUG
```

**Comment by babelouest** [comment]
Hello again @saohimank ,

I've added IPv6 support in the [branch 2.6](https://github.com/babelouest/ulfius/tree/2.6), check out the documentation: https://github.com/babelouest/ulfius/blob/2.6/API.md#instance-structure

Can you test this branch and give me feedback on this new feature?

**Comment by saohimank** [comment]
Hello @babelouest ,

Many thanks for the prompt response and supporting the feature in quick time. I tested the feature, but it has a bug. After fixing it, I could see that IPV6 binding is working fine. 

In ulfius.c, the bind_address6 was set to NULL (Line:1416) after initializing it. After commenting this line, it has worked. Could you please comment this line out and commit once again? 

https://github.com/babelouest/ulfius/blob/464fd410010b8b49921af779bd282a2e5acd0fc1/src/ulfius.c#L1416

   1414:  u_instance->bind_address6 = bind_address6;
   1415:  u_instance->network_type = network_type;
   **1416:  u_instance->bind_address6 = NULL; //Bug: Setting to NULL after initializing.**

**Comment by babelouest** [comment]
Thanks for noticing @saohimank ,

I've fixed the problem in the branch 2.6 and added a few tests that should prevent this kind of error.

**Comment by saohimank** [comment]
Hello @babelouest : Thanks once again for committing the fix. I've tested it again with the latest changes and it works like a charm :-)

**Comment by babelouest** [comment]
Awesome!
I'll release Ulfius 2.6 at the same time as Glewlwyd 2.0, but meanwhile you can use the branch 2.6.
