### ISSUE TITLE
HTTPS Client : Separating VerifyHost VerifyPeer 

### ISSUE THREAD

**Issue by saohimank** [babelouest/ulfius#105]
Hello @babelouest,

This is an enhancement request. This is for the case when ulfius acts as a HTTPS client. 

We have "check_server_certificate" flag to disable validation of server certificate and hostname. From the API documentation,

**check_server_certificate:  do not check server certificate and hostname if false (default true), used by ulfius_send_http_request**

But, as one single flag is used for server certificate and hostname validation, we would not able to able to enable/disable one of these two. 

The use case is, if the http_url is having IP address of the server and when the server's name in the certificate is a domain name, the host name validation fails as CURL compares IP address with the domain name. 

But, if one is fine with NOT doing hostname validation but still want to check the authenticity of the server certificate, we should be having separate flags for verifyhost and verifypeer, something similar to the one given below. 

https://github.com/saohimank/ulfius/commit/901cdf9a90e8a7e279a9d8e98c9b2e3e65087773#diff-fcf964e87453119035bbafcb08c55936

Could you please enhance ulfius to have this validation separate?

**Comment by babelouest** [comment]
Hello @saohimank ,

This is an very interesting enhancement, although I would like to avoid [this kind of bad experience](https://xkcd.com/1172/). What I suggest instead is adding a new flag in the `struct _u_request` called `verify_server`. The code would go like this:

```C
if (!copy_request->check_server_certificate) {
  if (curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYPEER, 0) != CURLE_OK || curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYHOST, 0) != CURLE_OK) {
    ulfius_clean_request_full(copy_request);
    curl_slist_free_all(header_list);
    curl_easy_cleanup(curl_handle);
   }
} else if (copy_request->verify_server & U_VERIFY_SERVER_PEER) {
  if (curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYPEER, 0) != CURLE_OK) {
    ulfius_clean_request_full(copy_request);
    curl_slist_free_all(header_list);
    curl_easy_cleanup(curl_handle);
  }
} else if (copy_request->verify_server & U_VERIFY_SERVER_HOST) {
  if (curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYHOST, 0) != CURLE_OK) {
    ulfius_clean_request_full(copy_request);
    curl_slist_free_all(header_list);
    curl_easy_cleanup(curl_handle);
  }
}
```

So existing installation that use check_server_certificate would still work the same.
If you want to use VerifyHost or VerifyPeer only, you would go like this:

```C
request->verify_server = U_VERIFY_SERVER_PEER; // Check only peer certificate
request->verify_server = U_VERIFY_SERVER_HOST; // Check only server hostname
```

How about that instead?

**Comment by saohimank** [comment]
Perfect, I was also concerned about the backward compatibility. Your suggestion is perfectly fine. If you can provide the changes, I will test and let you know :-)

**Comment by babelouest** [comment]
No problem, I'll do the changes soon. Although it will still be available only in the branch 2.6 until the official release.

As I was re-reading libcurl documentation, I also saw the following options: `CURLOPT_PROXY_SSL_VERIFYHOST` and `CURLOPT_PROXY_SSL_VERIFYPEER`, I will add them as well in a new `struct _u_request` variable with the same logic.

Also, I think I will name the new flag `check_server_certificate_flag` instead of `verify_server`

**Comment by babelouest** [comment]
Hello, I've pushed the new feature and fixed the documentation about the old `check_server_certificate`. Now the behavior is the following:
- if `struct _u_request.check_server_certificate` is false, then curl options `CURLOPT_SSL_VERIFYPEER` and `CURLOPT_SSL_VERIFYHOST` are off
- if `struct _u_request.check_server_certificate` is true and `struct _u_request.check_server_certificate_flag` isn't changed, then both `CURLOPT_SSL_VERIFYPEER` and `CURLOPT_SSL_VERIFYHOST` are set
- if you want to check only peer certificate, set `struct _u_request.check_server_certificate_flag` to `U_SSL_VERIFY_PEER`
- if you want to check only hostname, set `struct _u_request.check_server_certificate_flag` to `U_SSL_VERIFY_HOSTNAME`

The old documentation on `check_server_certificate` was ambiguous, I've fixed it to be more clear.

The new flags `struct _u_request.check_proxy_certificate` and `struct _u_request.check_proxy_certificate_flag` work the same, only for the proxy check.

**Comment by babelouest** [comment]
Here is the [updated documentation](https://github.com/babelouest/ulfius/blob/2.6/API.md#request-structure) for the new feature.

Thanks for your feedback

**Comment by saohimank** [comment]
Thank you so much :-) I will test and share the feedback soon.

**Comment by saohimank** [comment]
@babelouest : Hey, I have tested it and the changes are holding good. Thanks once again :-)

**Comment by babelouest** [comment]
Awesome, thanks for the feedback!
