### ISSUE TITLE
HTTPS Client: Configurable CA Certs Path

### ISSUE THREAD

**Issue by saohimank** [babelouest/ulfius#107]
Hello @babelouest ,

This is another enhancement request. Currently ulfius does not have the option to configure the CA certificates path. Due to which it becomes mandatory to append the remote server certificate to the standard "/etc/pki/tls/certs/ca-bundle.crt" file. 

If we have the option of configuring the CA certs path, having the ".pem" files in the path would be sufficient. Request you to add this option. 

**curl_easy_setopt(curl_handle, CURLOPT_CAPATH, "/path/to/certs") ;**

I can test and confirm once you provide the changes.

**Comment by babelouest** [comment]
Hello @saohimank ,

Can you check the [last commit](https://github.com/babelouest/ulfius/tree/2.6) on branch 2.6 and tell me if this fit your needs?

**Comment by saohimank** [comment]
Hello @babelouest ,

I think you have missed to copy the ca_path in "ulfius_duplicate_request" function. Due to which the value of ca_path is still coming as NULL in "ulfius_send_http_streaming_request" function. 

Request you to make this change. I will test it again once the change is available.

**Comment by babelouest** [comment]
My bad, this should be fixed now

**Comment by saohimank** [comment]
@babelouest : It is now working fine as expected :-) Thank you :-)

**Comment by babelouest** [comment]
This is what happen when you make a quick fix too quick :-)
