### ISSUE TITLE
Seeking general info regarding cmake build

### ISSUE THREAD

**Issue by akhileshsarda** [babelouest/ulfius#110]

**Comment by akhileshsarda** [comment]
Hi, I am using ulfius, orcania and yder in my project. To build them on another platform, I'm using cmake. Do I need to edit those cmakelists provided by all these three libraries?
Or how can make use of it? (I am using yocto, in which inheriting cmake)

**Comment by babelouest** [comment]
Hello,

IIRC, people have built ulfius on yocto Linux before.
Check out each project documentation to use the build options you might need for your use, like without systemd or jansson.

If you have problems during the build, don't hesitate to open new issue.
