### ISSUE TITLE
Can't use port 80?

### ISSUE THREAD

**Issue by hmkim123** [babelouest/ulfius#116]
There is a error when port number is 80.
The error message is like,
  ERROR: Ulfius - Error MHD_start_daemon, aborting
When I change port number to other value, it's running well.
There is no process use 80.
Could you tell me what I should do to use 80 for port number?
I need it because I can't use other port number for firewall reason.
Thank you for your help in advance.

**Comment by babelouest** [comment]
Hello @hmkim123 ,

In POSIX systems, you can't listen to ports below 1024 as a non-root user.

You have several ways to achieve this but they're not Ulfius related.

For example, you can redirect connections from port 80 to another port in your firewall, use CAP_NET_BIND_SERVICE or authbind.
In my case, I use apache mod_proxy_http to achieve this.

There are [several solutions](https://duckduckgo.com/?q=allow+user+to+use+port+80+linux&ia=web) on the internet, you will probably find yours.

**Comment by hmkim123** [comment]
Hello @babelouest ,
Thanks for your advice.
Have a nice day.
