### ISSUE TITLE
does ulfius blocks when sending a request to a remote API?

### ISSUE THREAD

**Issue by iceberg1369** [babelouest/ulfius#12]
I used ulfius in an event-driven app. I use ulfius to query a remote REST API in inside libev callback functions. so I am wondering whether calling ulfius_send_http_request inside events would block the whole loop or not?

**Comment by babelouest** [comment]
You're in luck, this was fixed yesterday https://github.com/babelouest/ulfius/commit/229a3100e3e6e231b4a2d562c2f83858620769af
Set the parameter `timeout` in your `struct _u_request` before sending the request and this should fix your problem. At least it fixed mine :)
