### ISSUE TITLE
Compilation error on openSUSE Tumbleweed systems with recent libcurl versions

### ISSUE THREAD

**Issue by mnhauke** [babelouest/ulfius#128]
Compilation fails on openSUSE Tumbleweed/Factory with recent libcurl (e.g. v7.65.1) versions.
https://build.opensuse.org/package/show/devel:libraries:c_c++/ulfius

``
[   73s] /home/abuild/rpmbuild/BUILD/ulfius-2.6.1/src/u_send_request.c: In function 'ulfius_send_http_streaming_request':
[   73s] /home/abuild/rpmbuild/BUILD/ulfius-2.6.1/src/u_send_request.c:379:21: error: call to '_curl_easy_setopt_err_curl_off_t' declared with attribute warning: curl_easy_setopt expects a curl_off_t argument for this option [-Werror=attribute-warning]
[   73s]   379 |                 if (curl_easy_setopt(curl_handle, CURLOPT_POSTFIELDSIZE_LARGE, copy_request->binary_body_length) != CURLE_OK) {
[   73s]       |                     ^
[   73s] lto1: all warnings being treated as errors
``

Full buildlog:
[ulfius-openSUSE-Tumbleweed-libcurl-compilation-error-full-buildlogtxt.txt](https://github.com/babelouest/ulfius/files/3388066/ulfius-openSUSE-Tumbleweed-libcurl-compilation-error-full-buildlogtxt.txt)

**Comment by babelouest** [comment]
That's an exotic one!

Does it work if you cast `copy_request->binary_body_length` to type `curl_off_t`?

The compiler doesn't complain with this on my side if I do that, but I don't have the issue in the first place...
If so I can cast all calls to `curl_easy_setopt` of the same type but I'd better be sure first.

**Comment by mnhauke** [comment]
You probably could reproduce this issue yourself if you use a recent gcc version (9.1.x)  with the following CFLAGS:

`-Wall -Werror -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=4 -g -DNDEBUG -O2 -g -DNDEBUG  -flto=4 -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now`


It's working fine if I cast `copy_request->binary_body_length` to type `curl_off_t`

**Comment by babelouest** [comment]
Thanks, I'll apply the patch soon then
