### ISSUE TITLE
restful without database

### ISSUE THREAD

**Issue by laoshaw** [babelouest/ulfius#129]
this is not a bug per se, I'm just curious about ulfius's use cases, I thought restful is more  relevant when database is used in the backend, otherwise what's the point of using RESTful/http-protocol at all? why not just use jsonrpc?

**Comment by babelouest** [comment]
Divide and conquer, ulfius is "just" a framework helpful to build REST APIs in C.

I made another framework called Hoel used for database abstraction: https://github.com/babelouest/hoel

Eventually, a database isn't mandatory to build REST APIs. Among other things, I use ulfius as a gateway with an Arduino, others use ulfius in addition to existing standalone applications to add more accesses, etc.
