### ISSUE TITLE
How do I build Ulfius 2.0?

### ISSUE THREAD

**Issue by silvioprog** [babelouest/ulfius#13]
Hello,

Firstly, thanks for this awesome job, I didn't know that this project existed.

So, I'm trying to compile Ulfius 2.0 with the following steps:

```bash
$ git clone https://github.com/babelouest/ulfius.git
$ cd ulfius/
$ git checkout 2.0
$ git submodule update --init
$ make
$ sudo make install
```
but it fails in the make step:

```bash
$ make
cd lib/orcania && make
make[1]: Entering directory '/home/silvioprog/dev/git/ulfius/lib/orcania'
cd ./src && make
make[2]: Entering directory '/home/silvioprog/dev/git/ulfius/lib/orcania/src'
gcc -c -fPIC -Wall -D_REENTRANT -O3  memory.c
gcc -c -fPIC -Wall -D_REENTRANT -O3  orcania.c
gcc -shared -Wl,-soname,liborcania.so -o liborcania.so.1.1 orcania.o memory.o -lc -ljansson
ln -sf liborcania.so.1.1 liborcania.so
make[2]: Leaving directory '/home/silvioprog/dev/git/ulfius/lib/orcania/src'
make[1]: Leaving directory '/home/silvioprog/dev/git/ulfius/lib/orcania'
cd lib/yder/src && make
make[1]: Entering directory '/home/silvioprog/dev/git/ulfius/lib/yder/src'
gcc -c -fPIC -Wall -D_REENTRANT -O3 yder.c
yder.c:33:21: fatal error: orcania.h: No such file or directory
compilation terminated.
Makefile:35: recipe for target 'yder.o' failed
make[1]: *** [yder.o] Error 1
make[1]: Leaving directory '/home/silvioprog/dev/git/ulfius/lib/yder/src'
Makefile:45: recipe for target 'libulfius.so' failed
make: *** [libulfius.so] Error 2
```

and make clean fails too:

```bash
$ make clean 
cd lib/orcania && make clean
make[1]: Entering directory '/home/silvioprog/dev/git/ulfius/lib/orcania'
cd ./src && make clean
make[2]: Entering directory '/home/silvioprog/dev/git/ulfius/lib/orcania/src'
rm -f *.o *.so liborcania.so liborcania.so.*
make[2]: Leaving directory '/home/silvioprog/dev/git/ulfius/lib/orcania/src'
cd ./test && make clean
make[2]: Entering directory '/home/silvioprog/dev/git/ulfius/lib/orcania/test'
rm -f *.o str_test split_test memory_test jansson_test valgrind.txt
make[2]: Leaving directory '/home/silvioprog/dev/git/ulfius/lib/orcania/test'
make[1]: Leaving directory '/home/silvioprog/dev/git/ulfius/lib/orcania'
cd lib/yder/src && make clean
make[1]: Entering directory '/home/silvioprog/dev/git/ulfius/lib/yder/src'
rm -f *.o *.so libyder.so libyder.so.*
make[1]: Leaving directory '/home/silvioprog/dev/git/ulfius/lib/yder/src'
cd ./src && make clean
make[1]: Entering directory '/home/silvioprog/dev/git/ulfius/src'
rm -f *.o *.so libulfius.so libulfius.so.*
make[1]: Leaving directory '/home/silvioprog/dev/git/ulfius/src'
cd ./examples && make clean
/bin/sh: 1: cd: can't cd to ./examples
Makefile:29: recipe for target 'clean' failed
make: *** [clean] Error 2
```

How do I build Ulfius.0 2?

Thank you!

**Comment by babelouest** [comment]
Hi Silvio,

Thanks for pointing out this bug, there was some errors in the `Makefile` and in the sub libraries.
You can pull the new code and also pull the submodules new code, it should work better now.

**Comment by babelouest** [comment]
Not quite, there's stilla problem with yder install, I'll get back to you soon with a fix

**Comment by babelouest** [comment]
OK so I updated the install procedure because there were too many problems if you don't have `liborcania` and `libyder` installed first. So now you need first to build and install them manually, then you should be good to build and install Ulfius.

Try with the last commit https://github.com/babelouest/ulfius/commit/225fc94125cf8233f05c58e7ce909eb6cb617076 or the further ones, this should work now.

**Comment by babelouest** [comment]
Hi Silvio,

Websockets public interface should not be modified now, if you want to give it a try, check the last commit in the branch 2.0 https://github.com/babelouest/ulfius/commit/2d64a89557f3057c4ba5ee80a8c383e178f6e2be and the `example_websockets` program source.

I need to implement tls and this should be good, feedbacks are welcome! :)

**Comment by silvioprog** [comment]
Hello @babelouest , sorry for late feedback.

I'm going to test the last changes asap. :-)

So, I'm developing a cross-platform C library for web development (including REST, SQL handling, OData, JSON... etc.) that will need some structures (e.g JWT, WebSockets) you already implemented in Ulfius (eg `u_websocket.c`), and it seems they can be changed to be more abstract allowing to use other libraries (eg mbedtls instead of openssl) and to be used by other frameworks, so, the Ulfius license allows it?

Thank you!

**Comment by babelouest** [comment]
Hi @silvioprog ,

Thanks for the feedback. I have no problem with adapting Ulfius to other libraries, as long as the LGPL license is respected.
AFAIK, the LGPL license says that you can use the library in a program with a different library, but if you make changes to Ulfius, you must provide the changes under the same license.
The best move would be to update the library so it can be used with `mbedtls` or `openssl` by only changing a build option, but the function signatures remain the same.

If you're curious, you can check my other projects, some may be useful: 
https://github.com/babelouest/hoel
https://github.com/babelouest/glewlwyd

**Comment by silvioprog** [comment]
Dude, thanks for fixing that, now it is working like a charm. :-)

I took a look at the projects and I think they will help me a lot, thanks for sharing them.

I need to read about websockets, I've used only HTTP 1.1, but in a near future I'm going to create a real-time application and probably the websockets will be the way.
