### ISSUE TITLE
Transfer-Encoding: chunked  /  ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by bouharb** [babelouest/ulfius#132]
**libcurl blocked when Transfer-Encoding: chunked** 
**ERR_INCOMPLETE_CHUNKED_ENCODING**

when I make a get from a server that returns a response block encoding, I get a status of 200 without result.

It's just that only for responses that use chunked in the headers.
I'm using the proxy example.

Great thanks in advance.

**Comment by bouharb** [comment]
the ulfius_write_body function works fine and return this result:

![Capture du 2019-08-07 12-30-18](https://user-images.githubusercontent.com/8422173/62616642-5b118180-b910-11e9-93c8-fe17a660f889.png)

But i get blanck page when i check url with browser or postman (with response headers -> Transfer-Encoding: chunked and ERR_INCOMPLETE_CHUNKED_ENCODING in console)

**Comment by babelouest** [comment]
I'm not sure I understand your context.
What part of ulfius are you using with the chunked response? Is it the server part or the client part?

Also, can you post a sample code to help me understand your problem?

**Comment by babelouest** [comment]
Also, you shouldn't post sample data that contains personal information on a public website.

**Comment by bouharb** [comment]
it's a fake data, also i use proxy exemple file with #define PROXY_DEST "https://reqres.in" or anodher host i get same bug when i get url who has Response Headers Transfer-Encoding: chunked.

For example : 

![res](https://user-images.githubusercontent.com/8422173/62622907-cd3d9280-b91f-11e9-974b-feeffcf575e6.PNG)

![ulfiusres](https://user-images.githubusercontent.com/8422173/62622919-d3cc0a00-b91f-11e9-9d2f-c33f1f0ecc8b.PNG)

**Comment by bouharb** [comment]
But the ulfius_write_body, ulfius_webservice_dispatcher functions works fine and return result.
Excuse me for my english which is not very good.
Great thanks in advance.

**Comment by babelouest** [comment]
I'm sorry I still don't understand what you want to do.

Can you explain what you want to do with ulfius?

Do you use the webservice or the client? Or both?

**Comment by bouharb** [comment]
I want to create a proxy similar to the example proposed in ulfius.

I used the same file, I just changed the url of the host

`#include <string.h>
#include <jansson.h>

#include <ulfius.h>
#include <u_example.h>

#define PORT 7799
#define PROXY_DEST "https://reqres.in"
`

**Comment by bouharb** [comment]
All requests work very well, but those with Response Headers Transfer-Encoding: chunked returns blank page

**Comment by babelouest** [comment]
To proxify chunked data, maybe you should use streaming instead of fixed size:

Client streaming data:

```C
/**
 * ulfius_send_http_streaming_request
 * Send a HTTP request and store the result into a _u_response
 * Except for the body which will be available using write_body_function in the write_body_data
 * return U_OK on success
 */
int ulfius_send_http_streaming_request(const struct _u_request * request, 
                                       struct _u_response * response, 
                                       size_t (* write_body_function)(void * contents, 
                                                                      size_t size, 
                                                                      size_t nmemb, 
                                                                      void * user_data), 
                                       void * write_body_data);
```

Server streaming service: https://github.com/babelouest/ulfius/blob/master/API.md#streaming-data

Check the [streaming example program](https://github.com/babelouest/ulfius/tree/master/example_programs/stream_example) to understand how to use streaming API.

The implementation isn't as easy though.
I tried to do something like that a few years ago, it didn't work as I expected so I abandonned it but you may find some ideas:
https://github.com/babelouest/carleon/blob/cda669aa9849d5d3de9f3ad23444ec7a6a8bf169/service-modules/service-motion.c

Afterwards, I thought of adding a `pthread_cond_t` and/or a mutex to synchronize reading and writing in the buffer between the threads.

Happy hacking!

**Comment by bouharb** [comment]
Thank you for your feedback and your clarifications.

**Comment by babelouest** [comment]
No problem, I'm closing the issue then.

Feel free to open a new issue if you need.
