### ISSUE TITLE
need the jwt.h file

### ISSUE THREAD

**Issue by bouharb** [babelouest/ulfius#133]
@babelouest 
I need the same jwt.h file version.

where can I find it ?
Great thanks in advance.

**Comment by babelouest** [comment]
Hello @bouharb ,

To use `example_callbacks/oauth2_bearer/glewlwyd_resource.c`, you need to install [libjwt](https://github.com/benmcollins/libjwt). I added the precision in the readme file. Thanks!

**Comment by bouharb** [comment]
Hello @babelouest,

libjwt package does not support ubuntu 18.04

![Capture du 2019-08-10 00-40-22](https://user-images.githubusercontent.com/8422173/62813085-40562d00-bb09-11e9-9aea-14875f0551ef.png)

**Comment by babelouest** [comment]
That's more a question to ask to the author of the library but I know at least two ways to install libjwt on Ubuntu 18.04 that work.

install from ubuntu repository
```shell
$ sudo apt install libjwt-dev
```

install from source: https://github.com/benmcollins/libjwt#build-instructions

**Comment by bouharb** [comment]
thanks but is missing params in struct config :

- accept_access_token 
- accept_client_token 

![Capture du 2019-08-10 05-16-52](https://user-images.githubusercontent.com/8422173/62816928-aacd9400-bb2e-11e9-8c85-3a535823c543.png)

**Comment by babelouest** [comment]
Fixed in https://github.com/babelouest/ulfius/commit/d807e89c145c7e8e976ef6fd5d18ca046191c764
The source was not up-to-date with the documentation

**Comment by bouharb** [comment]
Hello @babelouest ,

bug in converting to a pointer type

![Capture du 2019-08-10 05-36-42](https://user-images.githubusercontent.com/8422173/62825968-6be22180-bbb4-11e9-9b27-f29dd3025593.png)

**Comment by babelouest** [comment]
@bouharb , obviously there's a problem in your code, you pass wrong argument types to `ulfius_add_endpoint_by_val`, the [documentation](https://github.com/babelouest/ulfius/blob/master/API.md#callback-functions-management) has all the anwers.

You should also explore the [example programs](https://github.com/babelouest/ulfius/tree/master/example_programs) to understand the syntax.

And more generally, if you have a problem that doesn't have the answer in the documentation or the examples, do not answer in an issue that is about another subject, open a new issue.

And when you write an issue, post a sample code that can be copy/paste and the output result if relevant, no screenshots.

Thanks in advance

**Comment by bouharb** [comment]
@babelouest , I'm sorry but I took the same code proposed

- Error : cannot convert to a pointer type 

 ```
int main (int argc, char **argv) {

// Initialize the instance
struct _u_instance instance;

if (ulfius_init_instance(&instance, PORT, NULL, NULL) != U_OK) {
y_log_message(Y_LOG_LEVEL_ERROR, "Error ulfius_init_instance, abort");
return(1);
}
struct _glewlwyd_resource_config g_config;
g_config.method = G_METHOD_HEADER;
g_config.oauth_scope = "scope1";
g_config.jwt_decode_key = "secret";
g_config.jwt_alg = JWT_ALG_HS512;
g_config.realm = "example";
g_config.accept_access_token = 1;
g_config.accept_client_token = 0;

// Example, add an authentication callback callback_check_glewlwyd_access_token for the endpoint GET "/api/resource/"
ulfius_add_endpoint_by_val(&instance, "GET", NULL, "*",0, &callback_check_glewlwyd_access_token, (void*) g_config);
// Endpoint list declaration
.
.
.
 ```

**Comment by babelouest** [comment]
you probably forgot something like

```C
#include "glewlwyd_resource.h"
```
Can you open a new issue and follow the instructions from the template to help me help you?
