### ISSUE TITLE
Request information for auth_basic_user and auth_basic_password params 

### ISSUE THREAD

**Issue by bouharb** [babelouest/ulfius#135]
**auth params multiples_callbacks_example**

@babelouest Hello,
I wanted to know why I always have null values ​​with params auth_basic_user and auth_basic_password : GET http://localhost:6875/multiple/auth

And how can I retrieve the values ​​of the parameters of a get request

Thanks in advance

**Comment by babelouest** [comment]
The program `multiples_callbacks_example` relies on [HTTP Basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) for authentication.
On a browser, enter username `test` and password `testpassword` to get response 200.
If you use another http client, check its documentation to provide HTTP basic auth parameters.

In any case, the log output of the program will display the username and passwords provided.

The parameters of the request, the headers and the body can be accessed via the `struct _u_map` API as explained in the [documentation](https://github.com/babelouest/ulfius/blob/master/API.md#struct-_u_map-api)
