### ISSUE TITLE
Preflighted_requests

### ISSUE THREAD

**Issue by mickae1** [babelouest/ulfius#136]
Hi,

I would like to know if ulfius support natively the preflighted requests ?

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

Because for the moment, I have to make a callback for the OPTIONS methods. If I want this to work.

Micka,

**Comment by Knutselsmurf1** [comment]
A minor update:
```
ulfius_add_endpoint_by_val(&instance, "OPTIONS", NULL, "*", 0, &callback_options, NULL);

int callback_options(const struct _u_request *request, struct _u_response *response, void *user_data)
{
  u_map_put(response->map_header, "Access-Control-Allow-Origin", "*");
  u_map_put(response->map_header, "Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
  u_map_put(response->map_header, "Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Bearer, Authorization");
  u_map_put(response->map_header, "Access-Control-Max-Age", "1800");
  return U_CALLBACK_COMPLETE;
}
```
The following line must be added before return U_CALLBACK_CONTINUE; in every endpoint:

`u_map_put(response->map_header, "Access-Control-Allow-Origin", "*");`

**Comment by babelouest** [comment]
@Knutselsmurf1 , as mentioned in [the documentation](https://babelouest.github.io/ulfius/#instance-structure), you have the attribute `default_headers` in the `struct _u_instance` if you need header values to be added in all your endpoints response headers.

Example in [glewlwyd.c](https://github.com/babelouest/glewlwyd/blob/master/src/glewlwyd.c#L432):

```C
// Set default headers
u_map_put(config->instance->default_headers, "Access-Control-Allow-Origin", config->allow_origin);
u_map_put(config->instance->default_headers, "Access-Control-Allow-Credentials", "true");
u_map_put(config->instance->default_headers, "Cache-Control", "no-store");
u_map_put(config->instance->default_headers, "Pragma", "no-cache");
```
