### ISSUE TITLE
Error in libmicrohttpd execution. 

### ISSUE THREAD

**Issue by AnthuDuke** [babelouest/ulfius#138]
im trying to run this code on port 8080. but the ulfius_start_framework(&instance) is returning error status code 4 (which basically is Error in libmicrohttpd execution). I guess it fails to start the mhd daemon. Please instruct me doing the further step

**Comment by babelouest** [comment]
I can't help you without more information.
My first advice is to start from an example code and adapt it to your needs.

If you still have problems you don't understand, you can post a sample code to help me reproduce your issue.

**Comment by AnthuDuke** [comment]
struct _u_instance instance;
struct sockaddr_in ipv4addr;
memset(&ipv4addr, 0, sizeof(struct sockaddr_in));
ipv4addr.sin_family = AF_INET;
ipv4addr.sin_port = htons(PORT);
ipv4addr.sin_addr.s_addr = inet_addr(IPV4_ADDR);
if (ulfius_init_instance(&instance, PORT, &ipv4addr, NULL) != U_OK) {
rte_panic("[API] Unable to initialize socket");
}

ulfius_add_endpoint_by_val(&instance, "GET", "/test", NULL, 0,
&callback_test, NULL);

int status = ulfius_start_framework(&instance);
log_info("[API] Status %d", status);
if (status == U_OK) {
log_info("[API] Server started");
} else {
log_info("[API] Server Failed");
rte_panic("[API] Unable to start server");
}

ulfius_stop_framework(&instance);
ulfius_clean_instance(&instance);


this is the code

status returns with 4

**Comment by babelouest** [comment]
What is the value of `PORT`?
Can the user open socket on the specified port?

To help you, you can also enable [yder](https://github.com/babelouest/yder) logging, this may give you more information.

Example, before `ulfius_init_instance`, add the following line:

```C
y_init_logs("AnthuDuke Test", Y_LOG_MODE_CONSOLE, Y_LOG_LEVEL_DEBUG, NULL, "Initializing logs");
```

Then, close the logs after `ulfius_clean_instance`:

```C
y_close_logs();
```

**Comment by AnthuDuke** [comment]
how do i print them to a file?

**Comment by babelouest** [comment]
The [yder documentation](https://github.com/babelouest/yder) and the [examples](https://github.com/babelouest/yder/tree/master/examples) will help you understand how to use yder. It's very easy to use. 

To log into a file, here is an example:

```C
y_init_logs("AnthuDuke Test", Y_LOG_MODE_FILE, Y_LOG_LEVEL_DEBUG, "/tmp/AnthuDuke.log", "Initializing logs");
```

**Comment by AnthuDuke** [comment]
i get this error upon using that


error adding symbols: DSO missing from command line

**Comment by babelouest** [comment]
It's all explained in the documentation, you should add `-lyder` to your linker options:

```
$ gcc -o AnthuDuke AnthuDuke.c -lulfius -lyder
```

**Comment by AnthuDuke** [comment]
Ulfius - Error MHD_start_daemon, aborting

**Comment by babelouest** [comment]
Ca you answer those questions I asked later?

> What is the value of PORT?
> Can the user open socket on the specified port?

Also, can you post a sample code I can use as is to compile and reproduce your error?

**Comment by AnthuDuke** [comment]
code is as given here .. 

https://github.com/babelouest/ulfius/issues/138#issuecomment-526565695


PORT is 8080 and yes i can open socket on it

**Comment by babelouest** [comment]
The following code works fine:

```C
/*
 * file anthuduke.c
 * to compile: gcc -o anthuduke anthuduke.c -lulfius
 */
#include <stdio.h>
#include <string.h>
#include <arpa/inet.h>
#include <ulfius.h>
#include <yder.h>

#define PORT 8080
#define IPV4_ADDR "127.0.0.1"

static int callback_test(const struct _u_request * request, struct _u_response * response, void * user_data) {
  ulfius_set_string_body_response(response, 200, "Hello World!");
  return U_CALLBACK_CONTINUE;
}

int main () {
  struct _u_instance instance;
  struct sockaddr_in ipv4addr;
  memset(&ipv4addr, 0, sizeof(struct sockaddr_in));
  ipv4addr.sin_family = AF_INET;
  ipv4addr.sin_port = htons(PORT);
  ipv4addr.sin_addr.s_addr = inet_addr(IPV4_ADDR);
  if (ulfius_init_instance(&instance, PORT, &ipv4addr, NULL) != U_OK) {
    printf("[API] Unable to initialize socket\n");
  }

  ulfius_add_endpoint_by_val(&instance, "GET", "/test", NULL, 0, &callback_test, NULL);

  int status = ulfius_start_framework(&instance);
  printf("[API] Status %d", status);
  
  if (status == U_OK) {
    printf("[API] Server started\n");
    getchar();
  } else {
    printf("[API] Server Failed\n");
    printf("[API] Unable to start server\n");
  }

  ulfius_stop_framework(&instance);
  ulfius_clean_instance(&instance);
}
```

probably your problem lies elsewhere than ulfius.

**Comment by babelouest** [comment]
Hello @AnthuDuke , any update on your issue?

**Comment by AnthuDuke** [comment]
closing the issue
