### ISSUE TITLE
[Issue] Improve Sending data over websocket

### ISSUE THREAD

**Issue by mickae1** [babelouest/ulfius#139]
Hi,

When I want to send data over websocket in a while loop, I've to do something like that:

```
while(1){
....
iError = ulfius_websocket_wait_close(pSession->websocket_manager, 100);
if ( iError == U_WEBSOCKET_STATUS_OPEN) {
	printf("\t session %s send data 3\n", pSession->acToken);
	ulfius_websocket_send_message(pSession->websocket_manager, U_WEBSOCKET_OPCODE_TEXT, iSize, acMessage);
	printf("\t session %s send data 4\n", pSession->acToken);
}else{
	iError = ulfius_websocket_wait_close(pSession->websocket_manager, 1000);
	if ( iError == U_WEBSOCKET_STATUS_OPEN) {
		printf("\t session %s send data 5\n", pSession->acToken);
		ulfius_websocket_send_message(pSession->websocket_manager, U_WEBSOCKET_OPCODE_TEXT, iSize, acMessage);
		printf("\t session %s send data 6\n", pSession->acToken);
	}else{
		printf("\terror %d wait close for %s\n", iError, pSession->acToken);
	}
}
}
```

Why do I need to use the function  ulfius_websocket_wait_close ..... And sometime if the timeout is too short, i've to repeat the procedure to make it work.

I don't like to use ulfius_websocket_wait_close , because if you put a 2s timeout, it will wait 2s. 

ulfius 2.6.3

**Comment by babelouest** [comment]
Hello,

You don't have to use `ulfius_websocket_wait_close` if you don't want to. This function is part of the [Websocket status](https://github.com/babelouest/ulfius/blob/master/API.md#websocket-status) functions explained in the documentation.

The function `ulfius_websocket_wait_close` returns the value `U_WEBSOCKET_STATUS_OPEN` if the websocket is still open at the end of the specified timeout and `U_WEBSOCKET_STATUS_CLOSE` is the websocket is closed.

If you want to get the websocket status without timeout, you can simply use `ulfius_websocket_status`, this will return the same values than `ulfius_websocket_wait_close`. The intention of these functions is to avoid sending messages on a websocket that has been closed by the client or by the network.

In the [websocket example program](https://github.com/babelouest/ulfius/blob/master/example_programs/websocket_example/websocket_server.c), the server is intended to send a message every 2 seconds.

But you can definitely use another method to manage your messages sent to the websocket, that's up to your implementation.

**Comment by babelouest** [comment]
@mickae1 , does this answer your question?

**Comment by mickae1** [comment]
Yes thanks.

Le lun. 23 sept. 2019 à 18:59, Nicolas Mora <notifications@github.com> a
écrit :

**Comment by babelouest** [comment]
Ok, I'm closing the issue then.
