### ISSUE TITLE
gmtime_r needs to be enabled in MinGW-w64

### ISSUE THREAD

**Issue by nixbody** [babelouest/ulfius#141]
It seems that `gmtime_r` is not enabled by default in MinGW-w64. It needs either `_POSIX_C_SOURCE 200112L` or `_POSIX_THREAD_SAFE_FUNCTIONS` to be defined before including `<time.h>` in order to successfully compile `u_send_request.c` with MinGW-w64.

**Comment by babelouest** [comment]
Hello @nixbody 

Thanks for reporting the issue, I don't use ulfius on windows so I can't see if there are problems with it.

Can you post a pull request to fix the problem? You seem to know what and why, this would be helpful for the windows users.
