### ISSUE TITLE
extern C ??

### ISSUE THREAD

**Issue by LaMain66** [babelouest/ulfius#145]
Hello, and thanks for your work.

Did you intentionnaly decide to not add the classics "extern C" in your projects headers or is it an ommission ?
I'm trying to use 'ulfius' in a c++ project and none of libraries 'uflius' 'yder' and 'orcania' offer the 'extern c' in there headers...

LM66

**Comment by babelouest** [comment]
Hello @LaMain66 ,

Yes, it's by choice that I don't add the `extern "C"` linkage, but you should be able to add it yourself in your programs like this:

```C++
extern "C" {
  #include <yder.h>
  #include <ulfius.h>
}

void main() {
  // do you magic here
}
```

**Comment by babelouest** [comment]
@LaMain66 , does this answer your question?

**Comment by LaMain66** [comment]
Yes and No. I haven't yet encounter such choice. Do you mind give me your reasoning ?
But, anyway, i think a 'Note' for C++ users pointing they should enclose the include with a 'extern "C"' should be added in the doc.

**Comment by babelouest** [comment]
> Yes and No. I haven't yet encounter such choice. Do you mind give me your reasoning ?

The simplest answer is that Ulfius is a C library, not a C++ one.

I have been asked before to add prefix or code to facilitate integrating Ulfius to other languages (Pascal, Python, etc.). I prefer not to because I don't know how to maintain such code, and I don't want to add potential bugs or problems between languages, os, systems, etc.

>  But, anyway, i think a 'Note' for C++ users pointing they should enclose the include with a 'extern "C"' should be added in the doc.

Why note, but since I didn't have the utility before, nor the idea, I couldn't guess this would be a thing. Also, I almost never use C++.

Can you provide such Note I could add to the documentation?

**Comment by LaMain66** [comment]
> The simplest answer is that Ulfius is a C library, not a C++ one.
Yes, but it's really common to have compatibility to C++ when sharing C code.
And for the potential bug and problem, i'm not an expert but the "extern C" stuff is such massively used that i doubt any serious language as not takin it into account.
Also, the microhttpd header you use and almost all standard C header address the issue.
Don't wanna insist though ...

> Can you provide such Note I could add to the documentation?
I would write the note at the end of 'Ulfius API Documentation > header file'.
And just stated: Not for c++ users, enclose the #include 'ulfius.h' with a 'extern C {' block.

**Comment by babelouest** [comment]
Each time it's used, I see it like that:

```C
#ifdef __cplusplus
extern "C"
{
```

which is ok to me because of the `#ifdef __cplusplus`.

So on second thoughts, I'll make the change like this

**Comment by LaMain66** [comment]
Yes, perfect !
So, for your sharing, quality of code, packaging for linux system (i assume it's yours), and responsiveness, i would like to say:
Your rock man !

So long and keep up the good work.

**Comment by babelouest** [comment]
> packaging for linux system 

I'm part of the team that packages for Debian and derivative distribs, the other packages are from other nice people :-)
