### ISSUE TITLE
[Issue] Missing Code in  "simple_example"

### ISSUE THREAD

**Issue by LaMain66** [babelouest/ulfius#146]
At [Examples](https://github.com/babelouest/ulfius/tree/master/example_programs)
it is stated:
  simple_example: ..., json body parameters , ...

But, there is no such json code in associate main.c
Am i right ?

Regards.

**Comment by babelouest** [comment]
Hello,

You're correct, this is a typo. There is no JSON code in simple_example.
Thanks for the heads up!
