### ISSUE TITLE
About ulfius licence LGPL v2.1

### ISSUE THREAD

**Issue by alexe100** [babelouest/ulfius#148]
Hi
We are thinking to adopt ulfius for our commercial embedded system which runs on linux based operating system. Just to be sure, ulfius just depends on 

-Libmicrohttpd - LGPL
-Jansson - MIT
-Libcurl - ???
right?

We mean, can we develop webserver/websoket server/rest api using ulfius and keep source code closed?

Thanks
Alex

**Comment by babelouest** [comment]
Hello,

I can't speak for the other projects Ulfius depends on, you better should ask them directly if you want a straight answer. Although, libcurl uses a free MIT/X license: https://curl.haxx.se/docs/copyright.html

Concerning Ulfius itself, I use the LGPL license to allow closed source software to use it without restriction: you're free to use the library in your closed source program.

The only limitation is if you make changes to Ulfius source code itself, not the code linked to it, you will have to redistribute your modified version of Ulfius to your users.

Have fun!

**Comment by alexe100** [comment]
Great!
Thank you
