### ISSUE TITLE
request->map_cookie is always NULL

### ISSUE THREAD

**Issue by alexe100** [babelouest/ulfius#149]
Hi.
I have a callback procedure that returns a static index.html file (from SSD) inspired in source code from sheep_counter sample, like this:

int callback_get_cookietest (const struct _u_request * request, struct _u_response * response, void * user_data)
{
...
if(request->map_cookie == NULL) 
   printf("No cookies sent by browser\n"); 
else 
   printf("There are some cookies\n");
...
//Return page and set cookie (for now, it always set the cookie again)
ulfius_add_cookie_to_response(response, "session_id", "xxxx", NULL, 50000, "localhost", "/", 0, 0);
content_type = u_map_get((struct _u_map *)user_data, get_filename_ext(request->http_url));
response->binary_body = buffer;
response->binary_body_length = length;
u_map_put(response->map_header, "Content-Type", content_type);
response->status = 200;

I can see the html file on the firefox and firefox browser also receives the cookie (also tested using curl --verbose ...) but if I refresh the same url I never see the message "There are some cookies\n".
Using the cookies and header analyser plugin for firefox I can see that cookie is being sent to ulfius server. So, why is always request->map_cookie == NULL ?

Thanks 
Alex

**Comment by babelouest** [comment]
You probably have misused cookies management in your callbacks. Please note that `request->map_cookie` is never set to `NULL`, even if there's no cookies, you must use `u_map_get` to access those.

I've added the following two lines in the sheep_counter.c and I can see the cookie set when I refresh the page:

```diff
user@localhost:/usr/src/ulfius/example_programs/sheep_counter$ git diff -u
diff --git a/example_programs/sheep_counter/sheep_counter.c b/example_programs/sheep_counter/sheep_counter.c
--- a/example_programs/sheep_counter/sheep_counter.c
+++ b/example_programs/sheep_counter/sheep_counter.c
@@ -186,6 +186,7 @@ int callback_sheep_counter_start (const struct _u_request * request, struct _u_r
   ulfius_set_json_body_response(response, 200, json_body);
   json_decref(json_nb_sheep);
   json_decref(json_body);
+  ulfius_add_cookie_to_response(response, "session_id", "xxxx", NULL, 50000, "localhost", "/", 0, 0);
   return U_CALLBACK_CONTINUE;
 }
 
@@ -242,6 +243,7 @@ int callback_static_file (const struct _u_request * request, struct _u_response
   char  * file_path = msprintf("%s%s", STATIC_FOLDER, request->http_url);
   const char * content_type;
   
+  y_log_message(Y_LOG_LEVEL_DEBUG, "cookie sent: %s", u_map_get(request->map_cookie, "session_id"));
   if (access(file_path, F_OK) != -1) {
     f = fopen (file_path, "rb");
     if (f) {
```

In this case, the cookie is sent to the browser when the user clicks on the `Start counting` button.

**Comment by alexe100** [comment]
In fact I am also using u_map_get to and nothing is returned.

(Please, take my sample/test program inspired in sheep_counter in attachment. Not possible)

I am compiling it with this:
$gcc -o cookies cookies.c  -I ~/Downloads/ulfius/example_programs/include -I ~/Downloads/ulfius/include -lulfius -lorcania -ljansson -lyder

I also realized the following: if I compile simple_example using makefile  cookies work well but if I compile using  (similar) command above, cookies are not retrieved by ulfius server after delivered by browser.
Am I missing something in the gcc command line that deals with cookie support?
