### ISSUE TITLE
Any available easy way to process binary_body comming from html form post?

### ISSUE THREAD

**Issue by alexe100** [babelouest/ulfius#150]
Hello
I am getting a post action with binary body, coming from a html form (enctype=text/plain).
Hence, accessing binary body I can see this:

user_name=user1
password=abc123

Which are the contents of the form edit boxes (separated by \n)

My question is: does ulfius supplies any easy way to parse these kind of information?

Thanks

**Comment by babelouest** [comment]
Hello @alexe100 ,

As stated in [the documentation](https://github.com/babelouest/ulfius/blob/master/API.md#request-structure), you can access each body parameter sent in the request using the `map_post_body` variable of the `struct _u_request`.

See [struct _u_map API](https://github.com/babelouest/ulfius/blob/master/API.md#struct-_u_map-api) for `struct _u_map` documentation.

**Comment by alexe100** [comment]
I tried it but it is empty:

```
        const char ** keys = NULL;
        keys = u_map_enum_keys(request->map_post_body);
        for(int i=0; keys != NULL && keys[i] != NULL; i++) 
        {
            printf("KEYS: %s\n ",keys[i]);    
        }

        char request_body[request->binary_body_length + 1];
        o_strncpy(request_body, request->binary_body, request->binary_body_length);
        printf("BINARY BODY CONTENTS: %s\n ",request_body);   
```

request_body is filled but keys does not...

**Comment by babelouest** [comment]
If `request->binary_body` isn't parsed into parameters in the `map_post_body` structure, that may be because of your content-type encoding.

In your message below, you specify `enctype=text/plain`.

Although, Ulfius parses body parameters when the encoding type used is `application/x-www-form-urlencoded` or `multipart/form-data`.

**Comment by alexe100** [comment]
Let me try using application/x-www-form-urlencoded...

**Comment by alexe100** [comment]
No, keys are always empty. No problem, I am going to parse it by hand
Thanks a lot

**Comment by babelouest** [comment]
You can post a sample code to help me try to reproduce your problem, otherwise you can check the simple_example organ that has parameters send via HTTP POST

**Comment by alexe100** [comment]
Yes, I looked at simple_example for inspiration...
I have just "solved" it:
The following line results in empty keys in ulfius server:


Any encoding provided to the enctype property will result in empty keys.

But if I remove the enctype property (to use the default one which is application/x-www-form-urlencoded , I think) then the ulgius server can fill the keys!

<form method="post" action="" align="center" accept-charset="UTF-8">

Now it is working! :-)

Thank you very much babelouest
