### ISSUE TITLE
Any function to clean cookies?

### ISSUE THREAD

**Issue by Aventun** [babelouest/ulfius#151]
Hi all
Firstly I would like to say that ulfius is amazing! Congratulations for this work

I was looking for a way to delete cookies sent to the browser. Is there any function for that or do I have to read html/http protocol and do it by "hand"?

Or any sample that creates and cleans cookies?

Thank you
Av

**Comment by babelouest** [comment]
Hello @Aventun ,

There is no function to "delete a cookie" per se, but the best way is to send the same cookie key with an empty value, and an end of validity in the past:

```C
char * expires = "Sat, 10 Jan 1970 12:00:00 GMT"
ulfius_add_cookie_to_response(response, "cookie_key", "", expires, 0, "your_domain.tld", "/", 1, 0);
```

**Comment by Aventun** [comment]
It works!
Thank you
