### ISSUE TITLE
websocket too slow?

### ISSUE THREAD

**Issue by Aventun** [babelouest/ulfius#156]
Hi
Another problem I am experiencing is some king of slow websocket communication...

if (ulfius_websocket_wait_close(websocket_manager, 2000) == U_WEBSOCKET_STATUS_OPEN) 
{
	if (ulfius_websocket_send_message(websocket_manager, U_WEBSOCKET_OPCODE_TEXT, o_strlen(message.mesg_text),message.mesg_text) != U_OK) 
	{
		printf("Error sending message\n");
	}
}
else
{
	printf("Websocket is closed\n");
}

It seems that the problem is related to
ulfius_websocket_wait_close() call right?

Is there any other way to keep track of the sending operations without having this time penalty?
Thank you

**Comment by babelouest** [comment]
You don't have to use `ulfius_websocket_wait_close` if you don't want to, this function purpose is to wait until the websocket is closed or until the timeout ends.

As mentionned in the [documentation](https://github.com/babelouest/ulfius/blob/master/API.md#websocket-status), you can use `ulfius_websocket_status`. This function will immediately return `U_WEBSOCKET_STATUS_OPEN` or `U_WEBSOCKET_STATUS_CLOSE`.

**Comment by Aventun** [comment]
My mistake... 
ulfius_websocket_status is the function I need
Thanks a lot
