### ISSUE TITLE
undefined reference to `ulfius_websocket_wait_close'

### ISSUE THREAD

**Issue by alexe100** [babelouest/ulfius#157]
Hi
After compiling ulfius as:

cd orcania/
make && sudo make install
cd ../yder/
make && sudo make install
cd ../ulfius/
mkdir build
cd build
cmake ..
make && sudo make install

when I compile a program with websockets support:

...  -lulfius -lorcania -ljansson -lyder

 I get:

 undefined reference to `ulfius_websocket_wait_close'
undefined reference to `ulfius_websocket_send_message'
undefined reference to `ulfius_websocket_wait_close'
 undefined reference to `ulfius_websocket_send_fragmented_message'
undefined reference to `ulfius_websocket_wait_close'
undefined reference to `ulfius_websocket_send_message'
undefined reference to `ulfius_websocket_wait_close'
undefined reference to `ulfius_websocket_send_message'

Thanks
Alex

**Comment by babelouest** [comment]
Hello,

Websocket support must have been disabled because of missing dependencies.
Do you have all the libraries required with the correct version?
What system are you using?

**Comment by alexe100** [comment]
Linux ubuntu.Where is the info about those extra libs that must be installed and updated?

**Comment by alexe100** [comment]
Doing a make cleand and make all on the websocket sample, there is no error...

**Comment by babelouest** [comment]
Your cmake log is ok, websocket and uwsc are enabled.

The install documentation may help you with the requirements: https://github.com/babelouest/ulfius/blob/master/INSTALL.md#prerequisites

If it possible that you already have installed ulfius via the Ubuntu package?

**Comment by alexe100** [comment]
No, I always prefer buld from source. Hence apart from this command:

apt-get install libmicrohttpd-dev libjansson-dev libcurl4-gnutls-dev libgnutls28-dev libgcrypt20-dev

No other apt command was used to instal something related with ulfius. By the way, I have executed again the command above and the result is:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjansson-dev is already the newest version (2.12-1build1).
libmicrohttpd-dev is already the newest version (0.9.62-1).
libcurl4-gnutls-dev is already the newest version (7.64.0-2ubuntu1.2).
libgcrypt20-dev is already the newest version (1.8.4-3ubuntu1.1).
libgcrypt20-dev set to manually installed.
libgnutls28-dev is already the newest version (3.6.5-2ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by babelouest** [comment]
What does your `ulfius-cfg.h` says? It must be in the same folder where `ulfius.h` is installed: /usr/include or /usr/local/include

Also, what is the output of the make command?

**Comment by alexe100** [comment]
$sudo find / -iname 'ulfius-cfg.h'
/usr/local/include/ulfius-cfg.h
/usr/include/ulfius-cfg.h

$sudo find / -iname 'ulfius.h'
/usr/local/include/ulfius.h
/usr/include/ulfius.h



make clean
make
[ 10%] Building C object CMakeFiles/ulfius.dir/src/u_map.c.o
[ 20%] Building C object CMakeFiles/ulfius.dir/src/u_request.c.o
[ 30%] Building C object CMakeFiles/ulfius.dir/src/u_response.c.o
[ 40%] Building C object CMakeFiles/ulfius.dir/src/u_send_request.c.o
[ 50%] Building C object CMakeFiles/ulfius.dir/src/u_websocket.c.o
[ 60%] Building C object CMakeFiles/ulfius.dir/src/yuarel.c.o
[ 70%] Building C object CMakeFiles/ulfius.dir/src/ulfius.c.o
[ 80%] Linking C shared library libulfius.so
[ 80%] Built target ulfius
[ 90%] Building C object CMakeFiles/uwsc.dir/tools/uwsc/uwsc.c.o
[100%] Linking C executable uwsc
[100%] Built target uwsc

**Comment by babelouest** [comment]
```
$sudo find / -iname 'ulfius-cfg.h'
/usr/local/include/ulfius-cfg.h
/usr/include/ulfius-cfg.h

$sudo find / -iname 'ulfius.h'
/usr/local/include/ulfius.h
/usr/include/ulfius.h
```

You do have 2 versions of ulfius installed, the one in /usr/include must be an old version

**Comment by babelouest** [comment]
Does `sudo apt remove libulfius` remove something?

**Comment by alexe100** [comment]
I was trying to deploy the service/server on the target computer...
In the meanwhile, I reinstalled the operating system and ulfius and now it works! I dont know why because I followed the same steps but now it works.

Thanks a lot
