### ISSUE TITLE
Help: cross-compile as static libary for aarch64

### ISSUE THREAD

**Issue by gupta05** [babelouest/ulfius#165]
Hi,
This is not an issue but I am looking for some help. I am looking to compile this as static library to be able to use with c programs on aarch64 linux embedded target. Can you please tell me how to compile it as static library on x86 for aarch64 and all the headers that I will need to copy over? 
Thanks for your help,

**Comment by babelouest** [comment]
Hello @gupta05 ,

Thanks for asking, you made me realize the install documentation was incomplete. To build Ulfius in static mode you can either:

- Build with cmake using the `-DBUILD_STATIC=on` flag, see [install doc](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#cmake---multi-architecture)
- Build with Makefile using the `static*` targets, see [install doc](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#install-libulfius-as-a-static-archive)

[Yder](https://github.com/babelouest/yder) and [Orcania](https://github.com/babelouest/orcania) need similar compilation procedure. Concerning the dependencies (libmicrohttpd, jansson, libcurl), their documentation should mention how to build in static mode if applicable.

**Comment by gupta05** [comment]
Thanks for your response. How to cross compile ulfius for aarch64?

**Comment by babelouest** [comment]
I wouldn't know how to cross-compile, that's between you and your compiler.

A quick search gives me some results though: https://duckduckgo.com/?q=gcc+cross+compile+aarch64&ia=web

**Comment by gupta05** [comment]
Sorry for the confusion. I meant to ask if there was any variables I need to set for arch explicitly. I have the compiler but wasn't sure where to change it in ulfius makefile. Anyways I will figure out. Thanks.
