### ISSUE TITLE
unit testing

### ISSUE THREAD

**Issue by garylai00000** [babelouest/ulfius#167]
Is there any recommended unit testing tools for testing the APIs created by ulfius?

**Comment by babelouest** [comment]
The are several types for testing http APIs. It depends on what you want to test.

In ulfius and my other C projects, I use [check](https://libcheck.github.io/check/) to run tests and [valgrind](https://valgrind.org/) toi check for memory leaks and incorrect memory management.

You can check and reuse my tests if you need inspiration.
