### ISSUE TITLE
Drop Travis CI due to policy change

### ISSUE THREAD

**Issue by babelouest** [babelouest/ulfius#178]
I'm expecting to remove the Travis CI script in a near future.
Travis will [change](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) its business plan with open source projects and this new policy goes against my idea of open source philosophy.

Although I don't blame Travis to make their own decision on what business they want to run, that's not up to me and I respect that.

I will remove the [.travis.yml](https://github.com/babelouest/ulfius/blob/master/.travis.yml) before next release and keep only github actions.

The major change I see in this is that other platforms than x86_64 won't be tested. I haven't seen it possible to use other architectures with GitHub Actions in their documentation.

In particular, @nageshlop, your recent [pull requests](https://github.com/babelouest/ulfius/pull/175) will not be available after that. Do you know an alternative?

**Comment by nageshlop** [comment]
Hi @babelouest 
The ppc64le support for Github actions is in progress. Travis will continue to support opensource, and updated details available at link https://blog.travis-ci.com/oss-announcement.

**Comment by babelouest** [comment]
Hello @nageshlop , thanks for the feedback. Although I'm still worried about how Travis will handle open source projects after their migration, and the post you mention isn't very clear about what they intent to do.

In my case, I first had a travis-ci.org account which was migrated to a travis-ci.com account. Then, lately, when they started to drop open source support, I had a 10000 free plan credit which was consumed in a few days.
Then, out of nowhere, travis-ci moved my account back to travis-ci.org, without telling me why nor what it implicates. This would be cool, except that travis-ci.org still shows the message:

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

I'm kinda mixed up with all of this and I don't want to spend too much time on my projects CI while travis-ci is looking for a new business plan with open source projects, I mean all open source projects, not the one they choose worthy.

But again that's travis-ci's choice and I don't want to argue with that, they are wise enough to decide how to make profit.
