### ISSUE TITLE
YDERFLAG=1 doesn't work

### ISSUE THREAD

**Issue by avrhack** [babelouest/ulfius#180]
Building with "make YDERFLAG=1" fails - still looking for yder.h in include/ulfius.h

```
MMMini:ulfius mark$ make YDERFLAG=1

cd ./src && /Applications/Xcode.app/Contents/Developer/usr/bin/make
gcc -c -pedantic -std=gnu99 -fPIC -Wall -Werror -Wextra -D_REENTRANT -I../include -O3  ulfius.c
In file included from ulfius.c:30:
In file included from ../include/u_private.h:29:
../include/ulfius.h:71:12: fatal error: 'yder.h' file not found
  #include <yder.h>
           ^~~~~~~~
1 error generated.
make[1]: *** [ulfius.o] Error 1
make: *** [all] Error 2

```
On macOS Big Sur (11.1), Ulfius 2.7.1 cloned from github

**Comment by babelouest** [comment]
Hello @avrhack ,

I can't reproduce your problem, but it looks like your make command calls another command: `cd ./src && /Applications/Xcode.app/Contents/Developer/usr/bin/make`, and this subcommand doesn't pass the `YDERFLAG=1`.

you can try to run your real make command yourself:

```shell
MMMini:ulfius mark$ cd ./src && /Applications/Xcode.app/Contents/Developer/usr/bin/make YDERFLAG=1
```

**Comment by babelouest** [comment]
Hello @avrhack , any update on this issue?

**Comment by babelouest** [comment]
I'm choosing this issue due to its inactivity, feel free to reopen it with new information if needed
