### ISSUE TITLE
multithreading support in ulfius

### ISSUE THREAD

**Issue by ashishsaxenahsc** [babelouest/ulfius#190]
Hi @babelouest,

I have a query regarding REST server implementation in ulfius. Does it implement multithreading and  for each connection a new thread is spawned that will handle the new connection request ?

Thanks and Regards,
Ashish

**Comment by babelouest** [comment]
Hello @ashishsaxenahsc ,

By default, ulfius opens a new thread for each incoming connection, the thread is closed when the connection is finished.

If you want more control over the client connection management, you can use `ulfius_start_framework_with_mhd_options` detailed in the [documentation](https://github.com/babelouest/ulfius/blob/master/API.md#start-and-stop-webservice).

**Comment by babelouest** [comment]
Any feedback @ashishsaxenahsc ?

**Comment by ashishsaxenahsc** [comment]
Hi @babelouest,

Thanks for your reply. 
We just wanted to know about the multithreading implementation in ulfius. Thanks for the clarification.   

Regards,
Ashish
