### ISSUE TITLE
How to set http header content-type as application/json

### ISSUE THREAD

**Issue by zhangsen1860** [babelouest/ulfius#201]
Hello,  I need to send post request to other rest service, and the Content-Type application/json is required, so how to set the http header, and is the JANSSON required when compiling libulfius.so?

**Comment by babelouest** [comment]
Hello,

As stated in the [install documentation](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#cmake---multi-architecture), you need to use the flag `-DWITH_JANSSON=off` to disable Jansson support.

Also, to set the content-type header in the response, you can use `ulfius_set_response_properties` as explained in the [API documentation](https://github.com/babelouest/ulfius/blob/master/API.md#ulfius_set_response_properties)

Happy hacking!
