### ISSUE TITLE
cannot find -ldorcania

### ISSUE THREAD

**Issue by mehtajaimin** [babelouest/ulfius#217]
I am cross compling on ubuntu. I have been able to make and install orcania and I see it in /usr/local/lib but I get this error when trying to make yder 

arm-linux-gnueabihf/bin/ld : cannot find -ldorcania

I check the ldconfig -v and it does show the entry for lorcania. I am not able to figure out why the linker is not able to find lorcania.
I would be greatful  for any help on this.

**Comment by babelouest** [comment]
Hello @mehtajaimin 

Maybe running `ldconfig` could help to refresh the linker, or you can specify the orcania path during linking:

`gcc -o out source.c -lorcania -L/usr/local/lib`.

If none of those are working, can you post more information on what commands you are using, it might help to find a solution...

**Comment by mehtajaimin** [comment]
[linux-devkit]:/home/jaimin/SupportingLib/libulfius/yder> make
cd ./src && make
make[1]: Entering directory '/home/jaimin/SupportingLib/libulfius/yder/src'
arm-none-linux-gnueabihf-gcc --sysroot=/opt/ti-processor-sdk-linux-am335x-evm-07.03.00.005/linux-devkit/sysroots/armv7at2hf-neon-linux-gnueabi -shared -fPIC -Wl,-soname,libyder.so -o libyder.so.1.4.14 yder.o -lc -lorcania -lsystemd  --sysroot=/opt/ti-processor-sdk-linux-am335x-evm-07.03.00.005/linux-devkit/sysroots/armv7at2hf-neon-linux-gnueabi
/opt/ti-processor-sdk-linux-am335x-evm-07.03.00.005/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: cannot find -lorcania
collect2: error: ld returned 1 exit status
Makefile:85: recipe for target 'libyder.so' failed
make[1]: *** [libyder.so] Error 1
make[1]: Leaving directory '/home/jaimin/SupportingLib/libulfius/yder/src'
Makefile:43: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by mehtajaimin** [comment]
Thank you, I added the link directly in the make file and it was able to link. Thank you for looking into this.

**Comment by babelouest** [comment]
No problem, happy hacking!
