### ISSUE TITLE
[Question] this a thread blocking request library?

### ISSUE THREAD

**Issue by sirlordt** [babelouest/ulfius#220]
this library use pool events for handle request for not thread blocking way? Like libev or libhv?

**Comment by babelouest** [comment]
Hello,

In Ulfius, the pool event algorithm is handled by libmicrohttpd using the flags `MHD_USE_THREAD_PER_CONNECTION` and `MHD_USE_INTERNAL_POLLING_THREAD` see [source code](https://github.com/babelouest/ulfius/blob/master/src/ulfius.c#L1070).

How libmicrohttpd manages its pool events is documented in its website: https://www.gnu.org/software/libmicrohttpd/manual/libmicrohttpd.html#Thread-modes-and-event-loops

**Comment by babelouest** [comment]
@sirlordt , does this answer your question?

**Comment by sirlordt** [comment]
Yes thanks!!!.
