### ISSUE TITLE
Implicit declaration of function ‘o_strnullempty’ 

### ISSUE THREAD

**Issue by 2kPi** [babelouest/ulfius#231]
**Describe the issue**
Trying to compiling with `make` into `ulfius/example_programs/simple_example` folder

**To Reproduce**
 `make` into `ulfius/example_programs/simple_example` folder

**Expected behavior**
Compiling without error

**Screenshots**
![image](https://user-images.githubusercontent.com/5517670/170283793-69898fb4-bfc1-4913-9677-508675201e4f.png)
`

I tried to re install library but without any great result. 

Thanks for the help

**Comment by babelouest** [comment]
@2kPi , any update?

**Comment by le-cardinal** [comment]
got the same issue whereas ulfius is well installed on my distri

**Comment by babelouest** [comment]
I answered the question [below](https://github.com/babelouest/ulfius/issues/231#issuecomment-1137349049), did you try to cleanup your old versions of orcania and yder?

**Comment by pablomtzunc** [comment]
Manual installation fixed: https://github.com/babelouest/ulfius/blob/master/INSTALL.md#manual-install
