### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by Chargde-Porcupine** [babelouest/ulfius#236]
Is it possible to send emojis?

//for example
ulfius_set_string_body_response(response, 200, "🤗");

**Comment by babelouest** [comment]
Hello,

It doesn't seem so, if I try with the following callback function:

```C
int callback_get_test (const struct _u_request * request, struct _u_response * response, void * user_data) {
  ulfius_set_string_body_response(response, 200, "\U0001f602");
  return U_CALLBACK_CONTINUE;
}
```

the output is not an emojii, but something like `ðŸ˜‚`

I guess you would have to encode/decode the emojii to send it to the client.

**Comment by babelouest** [comment]
My bad, a nice person just told me I forgot to set the content-type properly, if you have a callback function like this:

```C
int callback_get_test (const struct _u_request * request, struct _u_response * response, void * user_data) {
  u_map_put(response->map_header, "Content-Type", "text/plain; charset=utf-8");
  ulfius_set_string_body_response(response, 200, "\U0001f602");
  return U_CALLBACK_CONTINUE;
}
```

You have an emoji displayed in the browser, yay!

**Comment by Chargde-Porcupine** [comment]
thank you very much!
