### ISSUE TITLE
Ulifus Request map_url parsing Issue: Request structure does not contain second parameter (key-value pair) onwards in request->map_url

### ISSUE THREAD

**Issue by vediyappan-villali** [babelouest/ulfius#237]
I am using the below URL and expecting all the key value pair should be in request->map_url. But I could see only 'key1' and 'value1' are present as a param (key-value pair).  request->map_url->nb_values always 1 irrespective of more number of parameters and I couldn't see second param (key-value pair) onwards.

http://127.0.0.1:1234/test?key1=value1&key2=value2&key3=value3

### URL used:
curl --request GET http://127.0.0.1:1234/test?key1=value1&key2=value2&key3=value3

### Logs:
check_request_params: Entry
check_request_params: Checking request parameters...
check_request_params: map url nb_values = 1
check_request_params: map url keys = key1
check_request_params: map url values = value1
check_request_params: map url lengths = 7

**Comment by babelouest** [comment]
Hello @vediyappan-villali ,

Maybe something's wrong in your curl request or somewhere else.

My first guess would be your curl request, if you don't use quotes to surround the url, the shell will interpret the `&` character as run-in-background.

Ulfius parses all url parameters as expected if I use the following callback function using the [Hello World example application](https://github.com/babelouest/ulfius#hello-world-example-application) base:

```C
int callback_hello_world (const struct _u_request * request, struct _u_response * response, void * user_data) {
  ulfius_set_string_body_response(response, 200, "Hello World!");
  printf("key1: %s\n", u_map_get(request->map_url, "key1"));
  printf("key2: %s\n", u_map_get(request->map_url, "key2"));
  printf("key3: %s\n", u_map_get(request->map_url, "key3"));
  return U_CALLBACK_CONTINUE;
}
```

And if I run the following curl command:
```shell
curl --request GET "http://127.0.0.1:8080/helloworld?key1=value1&key2=value2&key3=value3"
```

I get the following output in the console running `test`:

```shell
$ ./test 
Start framework on port 1234
key1: value1
key2: value2
key3: value3

End framework
```

**Comment by vediyappan-villali** [comment]
@babelouest Thank you for the reply. As you said, shell interpreted the & character as run-in-background. It started working after I use quotes around the URL.
