### ISSUE TITLE
[Issue]the example program sheep_counter can not be access by brower

### ISSUE THREAD

**Issue by qing8717** [babelouest/ulfius#240]
**Describe the issue**
When I run the example program sheep_counter,it does not work well.
1.In browser the URL "http://localhost:7437/static/index.html " has no response.
2.But the three URLs  "curl -X POST http://localhost:7437/sheep"  ,"curl -X PUT http://localhost:7437/sheep", "curl -X GET http://localhost:7437/sheep"  work well.

**To Reproduce**
buildenv@buildenv-VirtualBox:~/web_new/ulfius/example_programs/sheep_counter$ make test
LD_LIBRARY_PATH=../../src: ./sheep_counter
2022-09-09T08:18:48Z - sheep_counter INFO: Starting sheep_counter
Start sheep counter on port 7437

**System (please complete the following information):**
 - OS/Environment [Ubuntu 12.04,]
 - Ulfius Version [SHA-1: 92edd0dab1b9f0ad6ef7306e609eb6ba1acb99c2]
 - Source installation [build from source]
 - If applicable, what option did you use to build Ulfius [disable GnuTLS, disable curl]

**Comment by babelouest** [comment]
Indeed, there was a bug in `file_config.files_path` initialization, it's fixed in https://github.com/babelouest/ulfius/commit/8a6ac756afd4b3641061b42acbf9c949bd56dd1b, thanks for noticing!
