### ISSUE TITLE
ulfius.h and ulfius.c include pthread.h unconditionally

### ISSUE THREAD

**Issue by madebr** [babelouest/ulfius#243]
**Describe the issue**

`pthread.h` is not available on non-posix systems, such as win32.
This define blocks compiling ulfius with MSVC.

**To Reproduce**
Build ulfius with MSVC.

**Expected behavior**
It builds.

**System (please complete the following information):**
 - OS/Environment: Windows 10, Visual Studio 16 2019
 - Ulfius Version: master
 - Source installation: git [e.g. Distribution package, github package, build from source]
 - If applicable, what option did you use to build Ulfius: no websockets as not supported on Windows

**Additional context**
By wrapping the includes with a `#ifndef U_DISABLE_WEBSOCKET`, it builds again.

**Comment by babelouest** [comment]
Hello @madebr ,

Do the following patches work for you?

```patch
--- a/include/ulfius.h
+++ b/include/ulfius.h
@@ -51,12 +51,12 @@ extern "C"
 #ifndef U_DISABLE_WEBSOCKET
   #include <poll.h>
   #include <zlib.h>
+  #include <pthread.h>
   #ifndef POLLRDHUP
     #define POLLRDHUP 0x2000
   #endif
 #endif
 
-#include <pthread.h>
 #include <microhttpd.h>
 
 #if defined(_WIN32) && !defined(U_DISABLE_WEBSOCKET)
```

```patch
--- a/src/ulfius.c
+++ b/src/ulfius.c
@@ -30,7 +30,6 @@
 #endif
 
 #include <ctype.h>
-#include <pthread.h>
 #include <stdlib.h>
 #include <string.h>
```

**Comment by madebr** [comment]
Yes, as long as `pthread.h` is not included :)

Btw, is the use of `pthread.h` the only reason websockets are not supported on Windows?

**Comment by babelouest** [comment]
If I recall correctly, the missing function `poll` is another reason why
