### ISSUE TITLE
parameter non_interactive not working

### ISSUE THREAD

**Issue by madmaxstrange** [babelouest/ulfius#245]
**Describe the issue**
always wait for prompt !q

**Expected behavior**
close silently

**System (please complete the following information):**
 - OS/Environment Ubuntu 20
 - Ulfius Version 0.9 (from repository)
 - Source installation Distribution package

**Additional context**
I guess
in 
uwsc.c
switch  
lines 141 & 142
do {
    if (!config->non_interactive) {
to
if (!config->non_interactive) {
  do {
???

**Comment by babelouest** [comment]
Hello @madmaxstrange ,

Thanks for the issue, can you test with the last commit https://github.com/babelouest/ulfius/commit/7c8802020b8fbf69d3b2d33a06a52b9fec688a90 to check if the fix works?
