### ISSUE TITLE
[Issue] simple_example: build failed

### ISSUE THREAD

**Issue by dancesWithCycles** [babelouest/ulfius#248]
Hi folks,
Thank you so much for maintaining this repository. May I share the following issue with you?

**Describe the issue**
I am following the [readme](https://github.com/babelouest/ulfius/blob/master/example_programs/simple_example/README.md) for  the `simple_example` program but end up with failure.

**To Reproduce**
```
$ cd example_programs/simple_example
$ make test
```

Make replies with the following response.

```
cd ../../src && make debug CURLFLAG=1 GNUTLSFLAG=1
make[1]: Entering directory '/home/begerad/git/github/ulfius/src'
gcc -c -pedantic -std=gnu99 -fPIC -Wall -Werror -Wextra -Wconversion -D_REENTRANT -I../include -DDEBUG -g -O0  u_map.c
u_map.c: In function ‘u_map_put_binary’:
u_map.c:151:40: error: implicit declaration of function ‘o_strnullempty’ [-Werror=implicit-function-declaration]
  151 |   if (u_map != NULL && key != NULL && !o_strnullempty(key)) {
      |                                        ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:197: u_map.o] Error 1
make[1]: Leaving directory '/home/begerad/git/github/ulfius/src'
make: *** [Makefile:37: ../../src/libulfius.so] Error 2
```

**Expected behavior**
I expected `make` to build the `simple_example` program.

**System (please complete the following information):**
 - OS/Environment: Debian GNU/Linux 11 (bullseye)
 - Ulfius Version: see above
 - Source installation: #sudo apt install libulfius-dev uwsc --no-install-recommends

I am happy with each and every hint in the right direction.

Cheers!

**Comment by le-cardinal** [comment]
Hi, why the issue is closed with the reason duplicated since it looks like #247 is not about the same error ?
