### ISSUE TITLE
HTTP GET with array as response body

### ISSUE THREAD

**Issue by dancesWithCycles** [babelouest/ulfius#250]
Hi folks,
Thank you so much for maintaining this repository.

I am wondering what is the effort to transfer a [REST API route](https://v1gtfs.vbn.api.swingbe.de/routes-oset-limit?oset=1&limit=3) like this to libulfius.

I have not used arrays as response bodies of HTTP GET methods with libulfius yet. Do you know any existing examples?

Cheers!

**Comment by babelouest** [comment]
Hello,

You should check the documentation, there is a paragraph about [JSON integration](https://babelouest.github.io/ulfius/index.html#use-json-in-request-and-response-body) using Jansson, this may help you.

You also have the [sheep counter example program](https://github.com/babelouest/ulfius/tree/master/example_programs/sheep_counter) as a small example.

**Comment by dancesWithCycles** [comment]
Cheers @babelouest for the helpful advice!

For documentation reasons I created another example using a JSON array as response body in [ulfius](https://github.com/babelouest/ulfius) in this [repository](https://git.wtf-eg.de/dancesWithCycles/sandbox-libulfius/src/branch/main/libjansson).
