### ISSUE TITLE
How can I reopen a closed issue?

### ISSUE THREAD

**Issue by dancesWithCycles** [babelouest/ulfius#258]
Hi folks,
Is there a reason why I can not reopen this [issue](https://github.com/babelouest/ulfius/issues/253) or am I just to blind or tired?

Cheers!

**Comment by le-cardinal** [comment]
see question for me

**Comment by dancesWithCycles** [comment]
> see question for me

To be honest, I do not get that comment. May I ask you to try it again using other words?

**Comment by babelouest** [comment]
Hello,

I don't know if it's possible to re-open an issue and how to do it, but if an issue is closed and you need to expand it, I suggest to open an new issue and reference the closed one in it.

**Comment by dancesWithCycles** [comment]
Appreciate!
