### ISSUE TITLE
installation shouldn't require root -- and can static libraries me made?

### ISSUE THREAD

**Issue by openhacker** [babelouest/ulfius#26]
I'm using ulfius in an existing project.

In order to compile/run the app, I want the minimum manipulation of the target/build machine I need.

1) no root access
2) build .a in addition to .so libraries

**Comment by babelouest** [comment]
Hello,

To install ulfius without root access, simply change the PREFIX variable during install, example, to install in `/tmp/lib` directory:

```shell
$ make PREFIX=/tmp install
```

I've added a static archive build, check the `INSTALL.md` file for more instructions, let m know if it works fine. I don't need `.a` archives so I've ran some basic tests but there may be problems left.

**Comment by openhacker** [comment]
I think you'll harmlessly fail if you do
-ldconfig
in the Makefiles....

I forked the repos, I'll get back to you later (since I'm currently using
an older version)

marty

**Comment by babelouest** [comment]
That's right, the ldconfig fail if you're not root but I haven't find a proper command yet, `ldconfig -r  $(PREFIX)` doesn't work all the time and I had too much issues about that.
I'll add a warning in the documentation.

**Comment by babelouest** [comment]
Did you have time to check the static libraries? I'd like to close this issue soon if possible.

**Comment by openhacker** [comment]
yder and orcania does not have static libraries, and with the LPGL I'm not using static libraries.

But I definitely want to install as non-root.

${PREFIX}/{lib,include} are not being made if they don't exist.
If you use -ldconfig, you'll harmless fail (instead of:
/sbin/ldconfig
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
Makefile:51: recipe for target 'install' failed
make[1]: *** [install] Error 1

Also, you aren't versioning the soname -- do you want to break up the VERSION to major/minor (so soname is -soname=libuifius.so.${MAJOR}

**Comment by babelouest** [comment]
I've added static build for yder and orcania, but I'm not sure about the -ldconfig option, where to put it in the build process. My knowledge is not that deep, sorry.

Can you propose a patch that will fit your needs? It would be better for me to understand.

**Comment by openhacker** [comment]
If you add a hyphen in front of a make line, its ignored if it fails...(so
you don't have to install with make -k).

I don't have a "need" right now (I'm going to fork the repo and use my
fork).   But the whole idea of shared libraries is if the API changes, it
will incompatible if the MAJOR rev is in the soname (the idea is MINOR rev
changes are transparent, MAJOR rev changes will not run).

**Comment by babelouest** [comment]
I remember about the hyphen now, I used it a while ago and forgot about it. Now `orcania`, `yder` and `ulfius` have a safe ldconfig in the install process in their `Makefile`.

Thanks for the tip.
