### ISSUE TITLE
Non-ASCII symbols in test cookie

### ISSUE THREAD

**Issue by Karlson2k** [babelouest/ulfius#274]
https://github.com/babelouest/ulfius/blob/27be66105a53bede0a8f65adcc5f5d3991517355/test/framework.c#L6170

According to https://www.rfc-editor.org/rfc/rfc9110.html#section-5.5-4 any filed (header) should use ONLY US-ASCII symbols.
**NO** UTF-8 is allowed directly in the header. This applies for all headers, including `Cookie` and `Set-Cookie` headers, and for all HTTP versions: HTTP/1.1, HTTP/2 and HTTP/3.
Extended encoding would be possible with https://www.rfc-editor.org/rfc/rfc8187.html, but no "Cookie" or "Set-Cookie" is defined for "extended notation" (the extended notation should be like `Cookie: title*=UTF-8''%c2%a3%20and%20%e2%82%ac%20rates` and should use percent/URL encoding for non-ASCII).

Sometimes UTF-8 in the header may work by the chance, but there is no guarantee that it would not be broken at any moment by a correctly functioning client, server or proxy.

**Comment by babelouest** [comment]
Hello @Karlson2k ,

Right now, depending on `struct _u_instance.check_utf8`, ulfius validates a cookie header with the utf8 table. But since libmicrohttpd 1.0, non-valid cookies are rejected by libmicrohttpd, therefore not passed to ulfius.

If I understand your issue correctly, when using previous libmicrohttpd version, ulfius should always check if the cookie parameter is `US-ASCII` valid, all the time, not depending on the `check_utf8` parameter. Is that correct?

**Comment by Karlson2k** [comment]
Actually, there are two suggestions.

First (minimal): do not use non-compliant strings in testing, regardless of MHD versions, as they worked purely by the chance. Any distribution may apply its own patches to older MHD versions, and this would break your testing. You should not rely on processing of the wrong data in your testing (the opposite: you may rely on rejection of the broken data in the testing).
Instead, you may add more tests with **correct** cookie values, as described in https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.1.
Valid characters are `%x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E ; US-ASCII characters excluding CTLs, whitespace DQUOTE, comma, semicolon, and backslash`. Note that `=` can be freely used inside the cookie value. This would check that both client and server handle the data correctly, both in your code and in used libraries.
Note: the cookie parsing code in MHD was re-written to better match the RFC. It is not designed to reject UTF-8 specifically, and I'm not sure why it is rejected.

Second (enhancement): check user (application) input and reject invalid characters or strings for **both** the client part and the server part, to make sure that the whole chain can process the data correctly.
