### ISSUE TITLE
problem initializing submodules

### ISSUE THREAD

**Issue by pbn4** [babelouest/ulfius#3]
Hello, 

I'm not pro git user but I was struggling with the installation step:

    git submodule --init

It was returning a usage message for me in proj main directory.

It would be easier to simply run (it's just a hint):

    git clone --recursive https://github.com/babelouest/ulfius.git

**Comment by babelouest** [comment]
You're right, there was a typo in the documentation.

The correct command line I was thinking of is `git submodule update --init`, this is fixed in the last commit.

I admit that your command saves one step though, thanks for the tip :)

**Comment by babelouest** [comment]
fixed in https://github.com/babelouest/ulfius/commit/900278a7ee344d01289854dc917500675115f199
