### ISSUE TITLE
what's the  performance of ulfius. I need concurrency , how to evaluated  the amount of concurrency  of ulfius.

### ISSUE THREAD

**Issue by skylli** [babelouest/ulfius#30]
Good jod. i havet use u code in some of my project, i want to use it in my iot server. it need concurrency,how to evaluated  the amount of concurrency  of ulfius??

**Comment by babelouest** [comment]
I haven't made any real performance measures or benchmarks, so I can't tell you the amount of concurrency a program using Ulfius can handle. If you want, you can try to make some.

Usually, [ab](https://httpd.apache.org/docs/2.4/programs/ab.html) is a good program to test an http service.

**Comment by skylli** [comment]
thank you, i will try later.  Is  ulfius creat an thread to handle each http request ?

**Comment by babelouest** [comment]
Yes, there is one separate thread per connection.

**Comment by GitTibbe** [comment]
@babelouest but ulfius_send_http_request() will not be on a separate thread right? Only web sockets?

**Comment by babelouest** [comment]
@GitTibbe , ` ulfius_send_http_request()` is different from ulfius core webservice, it's the http client function and uses `libcurl` underneath. But it doesn't run any thread in the background.
Its behaviour is thread-safe according to [libcurl documentation](https://curl.haxx.se/libcurl/c/threadsafe.html).

Ulfius websocket server is another part of the framework. When the websocket connexion is established between the client and the server, a [single thread](https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L227) is executed to handle all incoming and outcoming websocket messages.
But the websocket thread is independent from the core webservice.
