### ISSUE TITLE
memory issue with websocket example

### ISSUE THREAD

**Issue by mmardinian** [babelouest/ulfius#44]
Hi Nicolas,

In the websocket example, when the websocket is created, we give user data:
"char * websocket_user_data = "my_user_data";"
But when this data is read in the callback functions, the 4 firsts bytes have been overwritten.

I managed to solve this issue, declaring the variable websocket_user_data as a global variable (getting it out of the function).

For your information, I work on an arm target. So this may come from my compiler.

Thank you for your work.

**Comment by babelouest** [comment]
There was a typo in the git comment, I can't reproduce this issue yet. where do you see the first 4 bytes overwritten? in the console or in the browser?

**Comment by mmardinian** [comment]
In the console, viewing logs.
If you can reproduce that, it may come from my compiler...
This really make me think to issues we can encounter with ARM stack management and local variable.

**Comment by babelouest** [comment]
That may be the problem indeed, `websocket_user_data` is a local variable of type `const char *` created in the function `callback_websocket`, which is not a good idea...

Can you modify in `callback_websocket` the creation of `websocket_user_data` with a `o_strdup("my_user_data");` for example, then `o_free` it in `websocket_onclose_callback`, and tell me if the memory problem remains?

**Comment by babelouest** [comment]
Using my last changes on the branch `fix-websocket`, I can't reproduce any memory leak. What compiler are you using?

**Comment by mmardinian** [comment]
Same for me, issue solved with the strdup.
I think the memory allocation for the data is way better than putting it in the stack.
My compiler is GCC but for an ARM processor.
Thanks again.

**Comment by babelouest** [comment]
That's right, never use local variables outside of the function! Thansk for the bug report :)
