### ISSUE TITLE
Installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by msaiducar** [babelouest/ulfius#47]
Hi,

I'm trying to install `ulfius` on my `Ubuntu 16.04`. However, while installing the deb package, it throws an error 
` libulfius depends on libmicrohttpd12 (>= 0.9.51); however:
  Package libmicrohttpd12 is not installed.`

When I checked the project page [1], the latest version of `libmicrohttpd12` for `Ubuntu 16.04` is `0.9.44`. Is there a way to install `ulfius` on `Ubuntu 16.04`?

[1] = https://launchpad.net/ubuntu/+source/libmicrohttpd

**Comment by babelouest** [comment]
Hello,

Ulfius has [no official package](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#debian-ish-packages) in Ubuntu 16.04, it was introduced in Ubuntu 17.10.

You can [install it manually](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#manual-install) though.
If you need websockets support, you'll have to compile a recent version of libmicrohttpd (minimum 0.9.53).
If you don't need websockets support, you can install the package libmicrohttpd-dev provided in Ubuntu 16.04

**Comment by babelouest** [comment]
Another solution is to install [Ulfius 2.3.4](https://github.com/babelouest/ulfius/releases/tag/v2.3.4) that has a [package for Ubuntu 16.04 xenial](https://github.com/babelouest/ulfius/releases/download/v2.3.4/ulfius-dev-full_2.3.4_Ubuntu_xenial_x86_64.tar.gz)

**Comment by babelouest** [comment]
@msaiducar , were you able to install ulfius correctly on Ubuntu 16.04?

**Comment by msaiducar** [comment]
@babelouest , I used the libcurl itself, I didn't tried to install ulfius due to restricted deadline. However, I will try to install asap. Thank you for your help.

**Comment by babelouest** [comment]
@msaiducar , any newson your install?
