### ISSUE TITLE
Unable to install in CentOS 7

### ISSUE THREAD

**Issue by eletious** [babelouest/ulfius#48]
Hello,

I am unable to build ulfius in CentOS 7 - using the makefile directions, I've installed Orcania, but yder fails to install with the following output:

`cd ./src && make
make[1]: Entering directory `/REDACTED/ulfius/lib/yder/src'
gcc -shared -Wl,-soname,libyder.so -o libyder.so.1.2.1 yder.o -lc -lorcania 
/usr/bin/ld: cannot find -lorcania
collect2: error: ld returned 1 exit status
make[1]: *** [libyder.so] Error 1
make[1]: Leaving directory `/REDACTED/ulfius/lib/yder/src'
make: *** [libyder.so] Error 2`

I'm building as root on a CI server - does this require that you build as a nonroot user?

**Comment by babelouest** [comment]
Usually, the error `cannot find -lorcania` can be fixed with re-running the command `sudo ldconfig`. Ulfius doesn't have to be compiled as root (although it can be), only the `make install` command has to be executed as root.

Maybe a better way for your automatisation is to install ulfius with the cmake script though.

```shell
$ mkdir build
$ cd build
$ cmake .. 
$ make && sudo make install
```

**Comment by eletious** [comment]
I attempted to use cmake initially, but centos7 uses the wrong version of cmake - >= 3.5 is required, but centos bundles 2.8.12.2

I also was unable to get it built after running ldconfig, though that should have made orcania available for use if I'm understanding this correctly.

**Comment by babelouest** [comment]
I assume you install it with the default params. i.e. in `/usr/local/lib`.

Do you have `liborcania*` files in this folder after installing Orcania? What are they?

**Comment by eletious** [comment]
I have liborcania.so.1.2.1 in that directory

**Comment by babelouest** [comment]
After a quick test on a Docker image, I found the solution and was able to install ulfius.

You need to add `/usr/local/lib` at the end of the file `/etc/ld.so.conf` and run `ldconfig -v` as root as explained here: https://serverfault.com/a/372998

Then you should be able to build properly orcania, yider, ulfius, then your application

**Comment by babelouest** [comment]
The packages I had to install were:
```
gnutls-devel
systemd-devel
libmicrohttpd-devel
jansson-devel
libcurl-devel
make
gcc
```

I'll update the documentation for CentOS.

**Comment by eletious** [comment]
The library exists now, and I was able to `make install`, however now the project I'm working on won't compile... undefined references to all of the functions I used from ulfius, which I now get in Ubuntu as well.  Must be doing something wrong on my end...

**Comment by babelouest** [comment]
I could make the simple example working in my case.
Maybe you had a `-lulfius` or a `ldconfig` missing.

**Comment by babelouest** [comment]
@eletious , any update?
