### ISSUE TITLE
ulfius_get_json_body_response doesn't response json

### ISSUE THREAD

**Issue by huahua-git** [babelouest/ulfius#50]
hello ,
      After calling ulfius_get_json_body_response, json cannot be returned. The code is as follows:
 ulfius_init_response(&response);
  res = ulfius_send_http_request(&req_list[0], &response);
  if (res == U_OK) {
      print_response(&response);
	  //json_body = ulfius_get_json_body_response(&response, &json_error);
	  printf("JSON String========: %c \n", ulfius_get_json_body_response(&response, &json_error));
  } else {
    printf("Error in http request: %d\n", res);
  }
  ulfius_clean_response(&response);

**Comment by babelouest** [comment]
Hello,

As mention in the [documentation](https://github.com/babelouest/ulfius/blob/master/API.md#json-body-in-request-and-response), `ulfius_get_json_body_response()` returns a `json_t *` which is a Jansson structure, so you must use jansson functions to manipulate it. You must also deallocate the returned value after use.

Example:
```C
ulfius_init_response(&response);
res = ulfius_send_http_request(&req_list[0], &response);
if (res == U_OK) {
  json_t * json_body = ulfius_get_json_body_response(&response, NULL);
  printf("JSON String========: %s \n", json_dumps(json_body, JSON_ENCODE_ANY));
  json_decref(json_body);
} else {
  printf("Error in http request: %d\n", res);
}
ulfius_clean_response(&response);
```

**Comment by huahua-git** [comment]
thank you!
