### ISSUE TITLE
Websocket opcode question

### ISSUE THREAD

**Issue by mmardinian** [babelouest/ulfius#52]
Hi,

Is it normal that both text and binary opcode for websocket has the same value?

`#define U_WEBSOCKET_OPCODE_TEXT     0x01
#define U_WEBSOCKET_OPCODE_BINARY   0x01`

Best regards,

Michael

**Comment by mmardinian** [comment]
Thank you

**Comment by babelouest** [comment]
Hello @mmardinian ,

The opcode bug has been fixed in the master branch and the [new release 2.3.7](https://github.com/babelouest/ulfius/releases/tag/v2.3.7).

I've made more tests with binary messages and it seems to work fine, but if you have other concerns about it, don't hesitate!
