### ISSUE TITLE
Building on FreeBSD

### ISSUE THREAD

**Issue by bluecub** [babelouest/ulfius#53]
Hi @babelouest 
Thanks for this awesome work
I was trying to install the ulfius library on FreeBSD (couldn't find it the port system) and it complained about systemd absence.
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Systemd (missing: SYSTEMD_LIBRARY SYSTEMD_INCLUDE_DIR)

Is there away to get around this to get work on freeBSD? and is there any plan for the future to support a freeBSD release as well?

Cheers

**Comment by babelouest** [comment]
Hello @bluecub ,

Thanks for the support!
The quick workaround is to build yder without systemd logging, then install ulfius:
```bash
$ git clone https://github.com/babelouest/yder.git
$ cd yder/
$ mkdir build
$ cd build
$ cmake .. -DWITH_JOURNALD=off
$ make && sudo make install
$ cd ../../ulfius # or cd /path/to/ulfius/source
$ mkdir build && cd build
$ cmake .. && make && sudo make install
```

This should fix your problem.
I'll also add the option `-DWITH_JOURNALD` to Ulfius CMake script as well so systems without systemd installed will be able to install Ulfius more easily.

About FreeBSD port of Ulfius, I would like to have one, although I don't know nor use any *BSD on a daily basis.
So I'm very cool with the idea, but I can't make it myself at the moment. If you volunteer to make a BSD port, that would be awesome!

**Comment by bluecub** [comment]
Thanks I will try it and let you know how it goes. Cheers

**Comment by babelouest** [comment]
It's even better than that, thanks to CMake's magic!

All you need is to pass the argument `-DWITH_JOURNALD=off` to cmake when you build Ulfius and this options will be passed to sub libraries, so Yder will be built without systemd support.

```shell
$ cd <ulfius source>
$ mkdir build
$ cd build
$ cmake -DWITH_JOURNALD=off ..
$ make && sudo make install
```

**Comment by bluecub** [comment]
Thanks so much, I really appreciate your support ... had another tiny issue which I will look into it as I’m not familiar with cmake. FreeBSD keeps user installed lib in /usr/local/lib and /usr/local/include and to link it is needed to add the path in cmake. 
Cheers

**Comment by bluecub** [comment]
The error I am getting is as below because it seems CMake does not find headers installed in /usr/local/include by default. On FreeBSD by default the local is **/usr/local/include**.

> >make 
> [  7%] Building C object orcania-build/CMakeFiles/orcania.dir/src/base64.c.o
> In file included from /home/code/app/lib/ulfius/build/orcania-src/src/base64.c:10:
> /home/code/app/lib/ulfius/build/orcania-src/src/../include/orcania.h:14:10: fatal error: 'jansson.h' file not found
> #include <jansson.h>
>          ^~~~~~~~~~~

The solution I guess must be something like this... yet I am not sure where I should add this

`if(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
  set(CMAKE_REQUIRED_INCLUDES "/usr/local/include" "/usr/include")
endif()`

**Comment by babelouest** [comment]
That's weird, because `/usr/include` is the default include path for Linux as well. So it should look in this path as well obviously.
How did you install jansson library? Using the source, a freeBSD port, something else?

**Comment by bluecub** [comment]
Yes using FreeBSD ports. All user installed libs go to /usr/local/lib and headers to /usr/local/include. In normal make I add those in the CFLags.

**Comment by bluecub** [comment]
$pkgconf --cflags jansson
-I/usr/local/include

**Comment by babelouest** [comment]
Sorry, I misread you last message and mixed `/usr/include` and `/usr/local/include`.

I could add a constant path in the include search but I'd rather keep this script as much system agnostic as possible.
Can you check, then maybe change your environment variable `C_INCLUDE_PATH` and see if it works?

See:
http://www.network-theory.co.uk/docs/gccintro/gccintro_23.html
https://docs.freebsd.org/info/gcc/gcc.info.Environment_Variables.html

**Comment by bluecub** [comment]
I want to add that path to which file in the package I should add it?
Thanks

**Comment by babelouest** [comment]
Can you try with the environment variable first?

**Comment by bluecub** [comment]
Environment variable solved that issue. Thanks :)

**Comment by babelouest** [comment]
@bluecub , if Ulfius builds completely on your FreeBSD, I'd close this issue then.

If you have other problems or concerns, don't hesitate to open a new issue on the repo.

**Comment by bluecub** [comment]
Thanks
