### ISSUE TITLE
Websocket example

### ISSUE THREAD

**Issue by frankycalo** [babelouest/ulfius#54]
Hi @babelouest 
compliment for fine work.

I could ask you how to compile websocket sample?
I tried compiling ulfius with websocket support, but when compiling the example I have an error (ulfuis is not available in websocket mode).

thanks for listening.

**Comment by babelouest** [comment]
Thanks,

To compile Ulfius with websocket support, you need libmicrohttpd 0.9.53 minimum.

I need more information to help you, can you tell me the system you're using and how you `"compile websocket sample"`?

You can also try to install Ulfius with another method see the [install doc](https://github.com/babelouest/ulfius/blob/master/INSTALL.md)

**Comment by babelouest** [comment]
@frankycalo , any update on your issue?
