### ISSUE TITLE
confusing static lib name

### ISSUE THREAD

**Issue by lnslbrty** [babelouest/ulfius#55]
Hello (.*),

Currently, I'm testing ulfius if it is usable for my project. But before, I need to port it to OpenWrt.
During my first steps I tried to fast build a usable static lib. After the build, my static lib was named `liblibulfius.a' which is a bit confusing.

The problematic line in CMakeLists.txt:
`set_target_properties(ulfius_static PROPERTIES OUTPUT_NAME libulfius)`

On Unix/Linux CMAKE_SHARED_LIBRARY_PREFIX_lang defaults to `lib'.

So replacing
`set_target_properties(ulfius_static PROPERTIES OUTPUT_NAME libulfius)`
with
`set_target_properties(ulfius_static PROPERTIES OUTPUT_NAME ulfius)`
should do the job.

After the first look I'm quite optimistic that it will be usable for my project.

**Comment by babelouest** [comment]
Hello @lnslbrty ,

Thanks for pointing out, I was probably not careful enough when I tested the static builds...

It seems that there is the exact same problem in [orcania](https://github.com/babelouest/orcania/blob/master/CMakeLists.txt#L93) and [hoel](https://github.com/babelouest/hoel/blob/master/CMakeLists.txt#L140) but not in [yder](https://github.com/babelouest/yder/blob/master/CMakeLists.txt#L77)... I'll fix this soon in the master branches.

Cheers

**Comment by babelouest** [comment]
Done, thanks again!
