### ISSUE TITLE
Can i sent an XML String with POST?

### ISSUE THREAD

**Issue by MoSad85** [babelouest/ulfius#60]
Hello,

ich want to handle XML comming from the POST method. 
can i do that with ulfius?

Thank you!!

**Comment by babelouest** [comment]
Hello @MoSad85 ,

Although there is no built-in functions in Ulfius to send/parse XML in request and response body, you can easily handle XML as long as it's stringified.

Don't forget to pass the Content-Type header `text/xml` or `application/xml` in the response, and check that this header is correct if you want to parse the request body.

For example with an `XML` as raw string:

```C
int my_callback_function(const struct _u_request * request,
                          struct _u_response * response,
                          void * user_data) {
  u_map_put(response->map_header, "Content-Type", "text/xml");
  ulfius_set_string_body_response(response, 200, "<root><node arg=\"param\">value</node></root>");
  return U_CALLBACK_CONTINUE;
}
```
