### ISSUE TITLE
Streaming with websocket

### ISSUE THREAD

**Issue by mmardinian** [babelouest/ulfius#61]
Hi,

I face some streaming issues using the websocket feature.
In my project, I stream audio files (Wav, 44100kHz, 16b = a lot of data).
I have sized the buffer load of the websocket to 1024Bytes and use a javascript interface as a client, to send these sample buffer to my application via ulfius websocket interface.

It's a lot of data to stream, and usually (in less than 2sec), some websocket bytes are missing on ulfius side.
In the function `ulfius_read_incoming_message`, I get incoherent values (message length, mask, opcode...). And that mess completely the streaming.
Playing with your code, I tried to force a lot of things like waiting for 1024 data byte each time to be delivered, checking using "poll".. but it's not enough.
I also checked that my client webpage doesn't saturate the bus, putting some sleeping time before each websocket send message, didn't worked either.

I am now completely lost and I don't know what else to test or fix.

Could you help me please?¨
Please let me know if you need further information.

Michael

**Comment by babelouest** [comment]
Hello,

I've never tested the websocket with binary data streaming, I'll run some tests to see if I have the same problem and therefore try to fix it.

What system/os are you using?

**Comment by babelouest** [comment]
I also need to know about your use case, when you say you stream data through the websocket. Is it a large file? Is it an io stream where you don't know the size? Is it from the client to the server? the opposite? Both?

**Comment by mmardinian** [comment]
Hi,

I finally got the chance to test the branch 2.4
And every seems to work fine.
Do you plan to make a new release with this?

Many Thanks,

Michael

**Comment by babelouest** [comment]
That's an excellent news!

I'll release ulfius 2.4 as soon as possible, I have to complete other new features though.
