### ISSUE TITLE
CMake error 

### ISSUE THREAD

**Issue by megpies** [babelouest/ulfius#64]
Hi @babelouest 
When you try to build the library from scratch (without having orcania, yder dynamic library installed already) you get 

>  CMake Error at build/yder-src/CMakeLists.txt:115 (add_subdirectory):
>   The binary directory
>     /home/tmp/ulfius/build/orcania-build
>   is already used to build a source directory.  It cannot be used to build
>   source directory
> 
>     /home/tmp/ulfius/build/orcania-src 
>   Specify a unique binary directory name

.The way I solved it is by commenting out in the ulfius CMakeLists.txt,
```
    #add_subdirectory(${orcania_SOURCE_DIR} ${orcania_BINARY_DIR})
    #include_directories(${orcania_SOURCE_DIR}/include)
    #include_directories(${orcania_SOURCE_DIR}/include)
    #add_dependencies(ulfius orcania)
    add_dependencies(ulfius orcania)
```
 apparently they exist in yder CMakeLists.txt and you can either have them in one place not both.

Thanks
Sam

**Comment by babelouest** [comment]
Thanks @megpies

I will update the cmake algorithm to do something like:

```
if (!orcania && !yder)
  install(yder)
end
```

So orcania won't be installed twice

**Comment by megpies** [comment]
Great library :)

**Comment by babelouest** [comment]
Thanks :sunglasses:
