### ISSUE TITLE
[Branch 2.4] Comparing size_t (unsigned long) to negative interger

### ISSUE THREAD

**Issue by bluecub** [babelouest/ulfius#67]
Hi @babelouest 

In branch 2.4 (u_websocket.c) mainly method: webscoketulfius_read_incoming_message in multiple places you are comparing size_t len to negative integers which throw error as size_t is unsigned long. 

Cheers,

**Comment by babelouest** [comment]
Thanks @bluecub ,

Although the branch 2.4 is not complete yet, but you're right, I have several places with this bug.

**Comment by bluecub** [comment]
Hi @babelouest 
would you mind if created new issues for branch 2.4? or it is too early as it is in development?

Thanks
