### ISSUE TITLE
[Brach 2.4] Clang issue: Unsinged comparison with int

### ISSUE THREAD

**Issue by bluecub** [babelouest/ulfius#70]
Hi @babelouest 
Another issue with comparing singed and unsigned types in websockets ... Thanks

> [ 71%] Building C object CMakeFiles/ulfius.dir/src/u_websocket.c.o
/home/code/app/lib/ulfius/src/u_websocket.c:206:23: error: comparison of integers of different signs: 'int' and 'const uint64_t' (aka 'const unsigned long') [-Werror,-Wsign-compare]
          for (i=0; i < data_len; i++) {
                    ~ ^ ~~~~~~~~
/home/code/app/lib/ulfius/src/u_websocket.c:324:24: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
        } else if (len != -1) {
                   ~~~ ^  ~~
2 errors generated.
*** Error code 1

**Comment by babelouest** [comment]
Thanks, that will be fixed soon.

Do you also test the new functionalities? If you see bugs or have ideas to improve them, feel free to tell me!

**Comment by bluecub** [comment]
Cheers... I will do. Thanks a lot

**Comment by babelouest** [comment]
@bluecub ,

Can you take a look at the current branch 2.4 ? There's a lot of websocket rework and I'd like to be sure it still works for you.
