### ISSUE TITLE
cppcheck issues in 2.4 branch

### ISSUE THREAD

**Issue by chipitsine** [babelouest/ulfius#71]
```
[example_programs/simple_example/simple_example.c:88] -> [example_programs/simple_example/simple_example.c:91]: (warning) Either the condition 'buffer!=NULL' is redundant or there is possible null pointer dereference: buffer.
[src/u_websocket.c:397] -> [src/u_websocket.c:386]: (warning) Either the condition 'message!=NULL' is redundant or there is possible null pointer dereference: message.
[src/u_websocket.c:397] -> [src/u_websocket.c:392]: (warning) Either the condition 'message!=NULL' is redundant or there is possible null pointer dereference: message.
[src/u_websocket.c:397] -> [src/u_websocket.c:397]: (warning) Either the condition 'message!=NULL' is redundant or there is possible null pointer dereference: message.
[src/ulfius.c:775] -> [src/ulfius.c:793]: (warning) Either the condition 'u_instance!=NULL' is redundant or there is possible null pointer dereference: u_instance.
```

**Comment by babelouest** [comment]
@chipitsine , do you use some special options with `cppcheck`? I don't always get your issues...

**Comment by babelouest** [comment]
@chipitsine , thanks by the way! :)

**Comment by chipitsine** [comment]
```cppcheck --force --enable=all .```

**Comment by babelouest** [comment]
@chipitsine ,

Can you take a look at the branch 2.4? There were a lot of rework lately and other verification would be better than one :p

Thanks in advance

**Comment by chipitsine** [comment]
Do you have some CI?

**Comment by babelouest** [comment]
Not yet, never took the time to setup one, although it would a good idea to have one...

**Comment by chipitsine** [comment]
[uwsc/uwsc.c:58] -> [uwsc/uwsc.c:61]: (warning) Either the condition 'buffer' is redundant or there is possible null pointer dereference: buffer.

**Comment by chipitsine** [comment]
https://github.com/babelouest/ulfius/pull/75

**Comment by chipitsine** [comment]
https://travis-ci.org/chipitsine/ulfius/jobs/435295861#L535

https://travis-ci.org/chipitsine/ulfius/jobs/435295861#L562
