### ISSUE TITLE
HTTPS Requests on client 

### ISSUE THREAD

**Issue by GitTibbe** [babelouest/ulfius#72]
Can you use this for secure HTTPS requests (POST/GET) for a client side with the same functions as non-secure?
Thanks in advance!

**Comment by babelouest** [comment]
Hello @GitTibbe ,

Yes, you can use the functions `ulfius_send_http_request` or `ulfius_send_http_streaming_request` either with secure or non secure urls.

The only option you can change set that relies on https requests is the `struct _u_request.check_server_certificate`, as explained in the [documentation](https://github.com/babelouest/ulfius/blob/master/API.md#request-structure). This is set to 1 by default. If you set it to 0 before calling `ulfius_send_http_request` or `ulfius_send_http_streaming_request`, then the server certificate will not be validated accordingly to your host policy.
