### ISSUE TITLE
Websocket is set to OFF but CMake fails

### ISSUE THREAD

**Issue by JAAM4494** [babelouest/ulfius#78]
ulfius-2.4.0/include/ulfius.h:43:27: fatal error: gnutls/gnutls.h: No such file or directory
compilation terminated.
CMakeFiles/ulfius.dir/build.make:62: recipe for target 'CMakeFiles/ulfius.dir/src/u_map.c.o' failed
make[2]: *** [CMakeFiles/ulfius.dir/src/u_map.c.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/ulfius.dir/all' failed
make[1]: *** [CMakeFiles/ulfius.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by babelouest** [comment]
My bad, I put this `#include` statement in the wrong place I guess, should be fixed in master now
