### ISSUE TITLE
cmake install not copying yuarel.h 

### ISSUE THREAD

**Issue by briandowns** [babelouest/ulfius#79]
It appears as though the cmake install script works great (and thank you for it) however it's not copying the yuarel.h to "/usr/local/include" on MacOS. I'm going to poke around some to see if I can figure out why however my cmake knowledge is limited. 

Thanks in advance for any and all assistance.

**Comment by babelouest** [comment]
Thanks for the report, can you copy paste the commands you're using and the result, I might have missed something in the build process...

**Comment by briandowns** [comment]
Thanks for responding so quickly. Here are the commands I'm running.

```
git clone git@github.com:babelouest/ulfius.git
cd ulfius
mkdir build
cd build
cmake -DWITH_JOURNALD=off -DWITH_RPM=off -DWITH_WEBSOCKET=off ..
make && sudo make install
```

**Comment by babelouest** [comment]
I think I got the problem, another issue with my install tests that don't handle websocket disabled. Should be fixed in the master branch.

**Comment by briandowns** [comment]
That worked great. Thank you so much for the insanely quick response and fix!
