### ISSUE TITLE
Different make failure on a separate jessie install

### ISSUE THREAD

**Issue by JeffHoover** [babelouest/ulfius#8]
## Pi Specs:
ARMv7 Processor rev 5 (v7l)
Raspbian GNU/Linux 8.0 (jessie), 
Linux version 4.4.41-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #942 SMP Mon Jan 9 15:00:25 GMT 2017

## It doesn't matter which example I choose:

'$ make test
cd ../../src && make debug
make[1]: Entering directory '/home/pi/ulfius/src'
gcc -c -fPIC -Wall -D_REENTRANT -I/usr/local/include -I../lib/orcania -I../lib/yder/src -DDEBUG -g -O0   ulfius.c
In file included from ulfius.c:27:0:
ulfius.h:30:24: fatal error: microhttpd.h: No such file or directory
 #include <microhttpd.h>
                        ^
compilation terminated.
Makefile:41: recipe for target 'ulfius.o' failed
make[1]: *** [ulfius.o] Error 1
make[1]: Leaving directory '/home/pi/ulfius/src'
Makefile:32: recipe for target 'libulfius.so' failed
make: *** [libulfius.so] Error 2
'

**Comment by babelouest** [comment]
It looks more like a problem with your installation than a problem with ulfius.

It says the file `/usr/include/microhttpd.h` is not present.

You could try by reinstalling mhd-dev:
```shell
$ sudo apt-get install --reinstall libmicrohttpd-dev
```

Or download libmicrohttpd from its [website](https://www.gnu.org/software/libmicrohttpd/), compile and install it manually.

**Comment by babelouest** [comment]
@JeffHoover , any update for this issue?

**Comment by JeffHoover** [comment]
Thanks for asking. That helped some. The next error I get is:

```
`$ make
cd ../../src && make debug
make[1]: Entering directory '/home/pi/ulfius/src'
gcc -c -fPIC -Wall -D_REENTRANT -I/usr/local/include -I../lib/orcania -I../lib/yder/src -DDEBUG -g -O0   ulfius.c
In file included from ulfius.c:27:0:
ulfius.h:31:21: fatal error: jansson.h: No such file or directory
 #include <jansson.h>
                     ^
compilation terminated.
Makefile:41: recipe for target 'ulfius.o' failed
make[1]: *** [ulfius.o] Error 1
make[1]: Leaving directory '/home/pi/ulfius/src'
Makefile:30: recipe for target 'libulfius.so' failed
make: *** [libulfius.so] Error 2
pi@raspberrypi:~/ulfius/examples/sheep_counter $ 
`
```

**Comment by babelouest** [comment]
Looks like a similar problem but with `jansson`, you could reinstall or compile jansson, or restart the install procedure from the beginning, maybe you missed something...

**Comment by JeffHoover** [comment]
Thanks. I'll have to look at it this weekend.

**Comment by babelouest** [comment]
OK, I'm closing this bug for now then. Let me know if you have similar issues

**Comment by JeffHoover** [comment]
Re-started installation process from scratch. *Everything worked the way
you would think it would* (once I realized that my LD_LIBRARY_PATH was
empty, and set it to /usr/local/lib)

Since I had problems with libmicrohttpd and then jansson, I must have
missed this step that installs the external dependencies:

apt-get install libmicrohttpd-dev libjansson-dev libcurl4-gnutls-dev


I should be all set now. Thank you for all your help with my noob problems!
Jeff

**Comment by babelouest** [comment]
No problem, making the library accessible for all is part of the project as well
