### ISSUE TITLE
Unable to differentiate between callback functions

### ISSUE THREAD

**Issue by zhemant** [babelouest/ulfius#80]
Hi @babelouest ,

I am facing issue with separating the callback function.
e.g. I have two url :
1. /example/1234  for this url call back function having url /example/:id should be invoked which it does.
2. /example/findByStatus?status=sold for this url call back function having url /example/findByStatus should be invoked which it doesn't. It invoked the same function as in e.g. 1 with url /example/:id

Is it meant to be this way or there is some issue here?

Thanks

**Comment by babelouest** [comment]
Hello,

In your case you need to set a higher priority to the second url `/example/findByStatus` and at the end of the callback for this url, return `U_CALLBACK_COMPLETE`.

https://github.com/babelouest/ulfius/blob/master/API.md#callback-functions-return-value

https://github.com/babelouest/ulfius/blob/master/API.md#multiple-callback-functions
