### ISSUE TITLE
How to avoid systemd check

### ISSUE THREAD

**Issue by TaruntejK** [babelouest/ulfius#82]
I am trying to build this library for sysVinit and I wont need journald for logging. So I need to avoid the systemd related checks in the yder. 

I've tried disabling JOURNALD in yder code as below 

> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index cce6408..ad05022 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -70,7 +70,7 @@ set(LIB_SRC
>  
>   dependencies
>  
> -option(WITH_JOURNALD "Check journald." ON)
> +option(WITH_JOURNALD "Check journald." OFF)
>  
>  if (WITH_JOURNALD)
>    include(FindSystemd)
> 

I am able to build yder succesfully with this change.
But when I build ulfius I am still getting 'configure' errors related to Systemd dependency, I guess it is again downloading yder-src as a part of 

> option(SEARCH_YDER "Search for Yder library" ON)
> if (SEARCH_YDER)
>     set(Yder_FIND_QUIETLY ON) # force to find Yder quietly
>     include(FindYder)
>     find_package(Yder 1.1 QUIET) # try to find Yder
>     if (NOT YDER_FOUND)
>         include(DownloadProject)
>         download_project(PROJ yder # ... otherwise, download archive
>                           URL "https://github.com/babelouest/yder/archive/v${YDER_VERSION_DOWNLOAD}.tar.gz"
>                           QUIET)
>         add_subdirectory(${yder_SOURCE_DIR} ${yder_BINARY_DIR})
>         include_directories(${yder_SOURCE_DIR}/include)
>         add_dependencies(ulfius yder)
>         set(YDER_LIBRARIES yder orcania)
>         include_directories(${yder_BINARY_DIR})
>     else()
>         set(LIBS ${LIBS} ${YDER_LIBRARIES})
>         include_directories(${YDER_INCLUDE_DIRS})
>     endif ()
>     target_link_libraries(ulfius ${LIBS} ${YDER_LIBRARIES})
> endif ()

 

Is there a way I can keep yder but remove systemd dependency while building ulfius.

I am using bitbake recipe to build it.

**Comment by TaruntejK** [comment]
I got it to build by adding ` option(WITH_JOURNALD "Check journald." OFF)` in CMakeLists.txt after 

>  download_project(PROJ yder # ... otherwise, download archive
>                            URL "https://github.com/babelouest/yder/archive/v${YDER_VERSION_DOWNLOAD}.tar.gz"
>                            QUIET)

**Comment by babelouest** [comment]
Even better, as mentionned in the [installation documentation](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#cmake---multi-architecture), you can simply pass the option when you call cmake:

```shell
$ mkdir build && cd build
$ cmake -DWITH_JOURNALD=off ..
```
