### ISSUE TITLE
Using parralel jobs in makefiles, library builds only on the second try

### ISSUE THREAD

**Issue by dlblv** [babelouest/ulfius#84]
As you can see, after build fails, the right config file is generated, so the second build succeeds. Can you fix that small problem?

![image](https://user-images.githubusercontent.com/20345406/49259888-2fb6c880-f44c-11e8-96d1-533cdc4c706a.png)

**Comment by babelouest** [comment]
I can't reproduce the issue, can you detail all the commands you run?

**Comment by dlblv** [comment]
> I can't reproduce the issue, can you detail all the commands you run?
First I checkout cloned repo to the last release version: `git checkout v2.4.4`
Then just cross compile it using `make CC=armv7l-unknown-linux-gnueabihf-gcc libulfius.so`
That's all

**Comment by babelouest** [comment]
I get it, your command `make -j16` forces to use 16 jobs in parallel.

In that case, it builds all targets at the same time, when it should first build the config file, then build the object file.

I've made a patch that will be release in next version 2.5 among other changes.
Meanwhile, as a workaround, you can either run the following command to build ulfius:
```shell
$ cd src
$ make ../include/ulfius-cfg.h
$ make CC=armv7l-unknown-linux-gnueabihf-gcc -j16 libulfius.so
```

That will force your build process to make the config file first, then build the library.

Thanks for the report!
