### ISSUE TITLE
Not an issue just suggestion

### ISSUE THREAD

**Issue by bluecub** [babelouest/ulfius#91]
Hi @babelouest 
Disclaimer: This is not an issue at all, just a suggestion.
I can see you are using gnuTLS, just wondering if you had the chance to check amazon aws s2n. It is a relatively new library, amazon released it as opensource. Very compact, secure and highly tested lib. I thought probably it might be useful.
[https://github.com/awslabs/s2n ](https://github.com/awslabs/s2n)

Thanks

**Comment by babelouest** [comment]
Thanks for the suggestion. I'll take a look at this. Although, now since ulfius 2.5, the dependency with GnuTLS is stronger, and libmicrohttpd beneath also depends on GnuTLS.
So the work required would be a nice challenge...

Although it's nice to know alternatives for fundamental parts.
