### ISSUE TITLE
Sheep example - POST not working properly again?

### ISSUE THREAD

**Issue by Syntaxerror1943** [babelouest/ulfius#94]
have the same problem with the sheep example. But i have set the 'Content-Type: application/json'. I tried it with the firefox client addon RESTClient and with curl:

`curl -X post -H 'Content-Type: application/json' -i 'http://192.168.2.119:7437/sheep' --data '{"nbsheep":5}'`

i got every time as return {"nbsheep":0}

json_nb_sheep seems to be not NULL with a simple printf test. 

Should i set some more header? I got no errors, i set the error pointer for the second value:

`ulfius_get_json_body_request(request, NULL)`

in the error struct the "text" value ist empty and source points to the string `<buffer>`

_Originally posted by @Syntaxerror1943 in https://github.com/babelouest/ulfius/issues/7#issuecomment-446925036_

**Comment by babelouest** [comment]
Hello @Syntaxerror1943 ,

It's not well described in the sheep counter readme but the POST data must be a single numeric value. In your case you should have something like:

```shell
$ curl -X post -H 'Content-Type: application/json' -i 'http://192.168.2.119:7437/sheep' --data '5'
```

As seen in the source code where the value is parsed: https://github.com/babelouest/ulfius/blob/master/example_programs/sheep_counter/sheep_counter.c#L179

**Comment by Syntaxerror1943** [comment]
works like a charm!

Thank you : )
