### ISSUE TITLE
Does ulfius support suse 11 sp3 and suse 12 sp1 or above?

### ISSUE THREAD

**Issue by kuncao** [babelouest/ulfius#97]
Hello very experts,
Does ulfius support suse 11 sp3 and suse 12 sp1 or above?
If ulfius  supports suse 11 sp3 and suse 12 sp1,how to install the related lib?
Please help to give the detail document.
Thanks a lot.

**Comment by babelouest** [comment]
Hello,

Although Ulfius is available in [OpenSuse](https://download.opensuse.org/repositories/devel:/libraries:/c_c++/openSUSE_Factory/src/ulfius-2.5.2-7.2.src.rpm.mirrorlist), I wouldn't for sure if Ulfius can be installed in Suse 11 SP3 or Suse 112 SP1 or above. The [prerequisites](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#prerequisites) section in the install documentation explains what you need to install Ulfius.

My best luck would be to ask Suse experts if those requirements are fulfilled.

But if you manage or not to install Ulfius on a Suse system, I'd be happy to know it.

**Comment by babelouest** [comment]
Hello @kuncao ,

Any luck installing Ulfius on suse 11 or 12?

**Comment by babelouest** [comment]
I took a look at [Suse customer center](https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=12.2&arch=x86_64) to search for the packages available on Suse 12 sp1.

The dependencies are present, but they are quite old. Especially for libmicrohttpd and jansson:
- [jansson 2.7](https://scc.suse.com/packages?arch=x86_64&name=SUSE+Linux+Enterprise+Server&package_id=1328356&query=jansson&version=12.1)
- [libcurl 7.37](https://scc.suse.com/packages?arch=x86_64&name=SUSE+Linux+Enterprise+Server&package_id=1784959&query=libcurl&version=12.1)
- [libmicrohttpd 0.9.30](https://scc.suse.com/packages?arch=x86_64&name=SUSE+Linux+Enterprise+Server&package_id=1325594&query=libmicrohttpd&version=12.1)
- [libgnutls 3.2.15](https://scc.suse.com/packages?arch=x86_64&name=SUSE+Linux+Enterprise+Server&package_id=1328233&query=libgnutls&version=12.1)

I couldn't find a packages database for Suse 11.

I don't know if Ulfius would compile on those platforms, maybe yes, but if not, I won't maintain changes in Ulfius source code to be available on such old platforms.

Hope that helps.
